// packages/vue/src/components/dialogs/InsertSymbolDialog.vue
<!--
  Insert Symbol dialog — ported from the upstream docx-editor Vue adapter.
-->
<template>
  <div v-if="isOpen" class="dialog-overlay" @mousedown.self="close">
    <div class="dialog symbol-dialog" @mousedown.stop @keydown.stop>
      <div class="dialog__header">
        <span class="dialog__title">{{ t("dialogs.insertSymbol.title") }}</span>
        <button class="dialog__close" :title="t('common.closeDialog')" @click="close">✕</button>
      </div>
      <div class="dialog__body">
        <!-- Search -->
        <input
          ref="searchRef"
          v-model="search"
          class="symbol-search"
          :placeholder="t('dialogs.insertSymbol.searchPlaceholder')"
          @keydown.escape="close"
        />

        <!-- Category tabs -->
        <div v-if="!search" class="symbol-tabs">
          <button
            v-for="cat in categories"
            :key="cat.name"
            class="symbol-tab"
            :class="{ active: activeCategory === cat.name }"
            @mousedown.prevent="activeCategory = cat.name"
          >
            {{ t(cat.nameKey) }}
          </button>
        </div>

        <!-- Symbol grid -->
        <div class="symbol-grid">
          <button
            v-for="sym in displayedSymbols"
            :key="sym.char"
            class="symbol-cell"
            :class="{ selected: selectedSymbol === sym.char }"
            :title="sym.name"
            @click="selectedSymbol = sym.char"
            @dblclick="insertSymbol(sym.char)"
          >
            {{ sym.char }}
          </button>
          <div v-if="displayedSymbols.length === 0" class="symbol-empty">
            {{
              search
                ? t("dialogs.insertSymbol.noResults", { query: search })
                : t("dialogs.insertSymbol.noResultsEmpty")
            }}
          </div>
        </div>

        <!-- Preview & info -->
        <div v-if="selectedSymbol" class="symbol-preview">
          <span class="symbol-preview__char">{{ selectedSymbol }}</span>
          <span class="symbol-preview__info"
            >U+{{
              selectedSymbol.codePointAt(0)?.toString(16).toUpperCase().padStart(4, "0")
            }}</span
          >
        </div>

        <!-- Recent -->
        <div v-if="recentSymbols.length > 0 && !search" class="symbol-recent">
          <div class="symbol-recent__label">{{ t("dialogs.insertSymbol.recent") }}</div>
          <button
            v-for="s in recentSymbols"
            :key="s"
            class="symbol-cell symbol-cell--small"
            @dblclick="insertSymbol(s)"
            @click="selectedSymbol = s"
          >
            {{ s }}
          </button>
        </div>

        <div class="dialog__actions">
          <button class="dialog__btn" @click="close">{{ t("common.cancel") }}</button>
          <button
            class="dialog__btn dialog__btn--primary"
            @mousedown.prevent="insertSymbol(selectedSymbol)"
            :disabled="!selectedSymbol"
          >
            {{ t("common.insert") }}
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, watch, nextTick } from "vue";
import { useTranslation } from "../../i18n";
import { SYMBOL_CATEGORIES, filterSymbols, type SymbolSearchEntry } from "@stll/folio-core/symbols";

const { t } = useTranslation();

const props = defineProps<{ isOpen: boolean }>();
const emit = defineEmits<{
  (e: "close"): void;
  (e: "insert", symbol: string): void;
}>();

const searchRef = ref<HTMLInputElement | null>(null);
const search = ref("");
const activeCategory = ref("Common");
const selectedSymbol = ref("");
const recentSymbols = ref<string[]>([]);

const categories = SYMBOL_CATEGORIES;

const displayedSymbols = computed<SymbolSearchEntry[]>(() => {
  if (search.value) {
    return filterSymbols(search.value);
  }
  const cat = categories.find((c) => c.name === activeCategory.value);
  return cat ? cat.symbols.map((symbol) => Object.assign({}, symbol, { category: cat.name })) : [];
});

watch(
  () => props.isOpen,
  async (open) => {
    if (open) {
      await nextTick();
      searchRef.value?.focus();
    }
  },
);

function close() {
  emit("close");
}

function insertSymbol(sym: string) {
  if (!sym) return;
  // Track recent
  recentSymbols.value = [sym, ...recentSymbols.value.filter((s) => s !== sym)].slice(0, 10);
  emit("insert", sym);
}
</script>

<style scoped>
.dialog-overlay {
  position: fixed;
  inset: 0;
  background: var(--doc-overlay);
  z-index: 300;
  display: flex;
  align-items: center;
  justify-content: center;
}
.dialog {
  background: var(--doc-surface);
  border-radius: 8px;
  box-shadow: 0 8px 30px var(--doc-shadow);
  max-width: 90vw;
}
.symbol-dialog {
  width: 480px;
}
.dialog__header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 12px 16px;
  border-bottom: 1px solid var(--doc-border);
}
.dialog__title {
  font-weight: 600;
  font-size: 14px;
  color: var(--doc-text);
}
.dialog__close {
  border: none;
  background: transparent;
  cursor: pointer;
  font-size: 14px;
  color: var(--doc-text-muted);
  width: 24px;
  height: 24px;
  display: flex;
  align-items: center;
  justify-content: center;
  border-radius: 4px;
}
.dialog__close:hover {
  background: var(--doc-bg-hover);
}
.dialog__body {
  padding: 16px;
}
.dialog__actions {
  display: flex;
  justify-content: flex-end;
  gap: 8px;
  margin-top: 12px;
}
.dialog__btn {
  padding: 6px 16px;
  border: 1px solid var(--doc-border-dark);
  border-radius: 4px;
  cursor: pointer;
  font-size: 13px;
  background: var(--doc-surface);
}
.dialog__btn--primary {
  background: var(--doc-primary);
  color: var(--doc-on-primary);
  border-color: var(--doc-primary);
}
.dialog__btn--primary:hover {
  background: var(--doc-primary);
}
.dialog__btn--primary:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

.symbol-search {
  width: 100%;
  padding: 6px 10px;
  border: 1px solid var(--doc-border-dark);
  border-radius: 4px;
  font-size: 13px;
  outline: none;
  box-sizing: border-box;
  margin-bottom: 8px;
}
.symbol-search:focus {
  border-color: var(--doc-primary);
}

.symbol-tabs {
  display: flex;
  gap: 2px;
  margin-bottom: 8px;
  flex-wrap: wrap;
}
.symbol-tab {
  padding: 4px 8px;
  border: none;
  border-radius: 4px;
  background: transparent;
  cursor: pointer;
  font-size: 11px;
  color: var(--doc-text-muted);
}
.symbol-tab:hover {
  background: var(--doc-bg-hover);
}
.symbol-tab.active {
  background: var(--doc-accent-bg);
  color: var(--doc-accent);
  font-weight: 600;
}

.symbol-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(36px, 1fr));
  gap: 2px;
  max-height: 240px;
  overflow-y: auto;
  border: 1px solid var(--doc-border);
  border-radius: 4px;
  padding: 4px;
}
.symbol-cell {
  width: 36px;
  height: 36px;
  display: flex;
  align-items: center;
  justify-content: center;
  border: 1px solid transparent;
  border-radius: 4px;
  cursor: pointer;
  font-size: 18px;
  background: transparent;
}
.symbol-cell:hover {
  background: var(--doc-bg-hover);
  border-color: var(--doc-border-dark);
}
.symbol-cell.selected {
  background: var(--doc-primary-light);
  border-color: var(--doc-primary);
}
.symbol-cell--small {
  width: 28px;
  height: 28px;
  font-size: 14px;
}
.symbol-empty {
  grid-column: 1/-1;
  text-align: center;
  padding: 24px;
  color: var(--doc-text-subtle);
  font-size: 13px;
}

.symbol-preview {
  display: flex;
  align-items: center;
  gap: 12px;
  margin-top: 8px;
  padding: 8px 12px;
  background: var(--doc-bg);
  border-radius: 4px;
}
.symbol-preview__char {
  font-size: 28px;
}
.symbol-preview__info {
  font-size: 12px;
  color: var(--doc-text-muted);
  font-family: monospace;
}

.symbol-recent {
  display: flex;
  align-items: center;
  gap: 4px;
  margin-top: 8px;
  flex-wrap: wrap;
}
.symbol-recent__label {
  font-size: 11px;
  color: var(--doc-text-subtle);
  margin-right: 4px;
}
</style>

// packages/react/src/components/dialogs/InsertSymbolDialog.tsx
import { useState } from "react";
import { useTranslations } from "use-intl";

import { SYMBOL_CATEGORIES, filterSymbols, type SymbolSearchEntry } from "@stll/folio-core/symbols";

import { useFolioUI } from "../../ui/folio-ui";
import {
  DIALOG_BACKDROP_CLASS,
  DIALOG_BODY_CLASS,
  DIALOG_FOOTER_CLASS,
  DIALOG_INPUT_CLASS,
  DIALOG_POPUP_CLASS,
  DIALOG_PRIMARY_BUTTON_CLASS,
  DIALOG_SECONDARY_BUTTON_CLASS,
  DIALOG_TITLE_CLASS,
  useCloseOnDialogOpenChange,
} from "./dialogChrome";

export type InsertSymbolDialogProps = {
  isOpen: boolean;
  onClose: () => void;
  onInsert: (symbol: string) => void;
};

const RECENT_LIMIT = 10;

/** Format a character as its `U+XXXX` code point label. */
function codePointLabel(char: string): string {
  return `U+${(char.codePointAt(0) ?? 0).toString(16).toUpperCase().padStart(4, "0")}`;
}

export function InsertSymbolDialog({ isOpen, onClose, onInsert }: InsertSymbolDialogProps) {
  const {
    Root: Dialog,
    Portal: DialogPortal,
    Backdrop: DialogBackdrop,
    Popup: DialogPopup,
    Title: DialogTitle,
  } = useFolioUI().Dialog;
  const handleOpenChange = useCloseOnDialogOpenChange(onClose);
  const t = useTranslations("folio");
  const [search, setSearch] = useState("");
  const [activeCategory, setActiveCategory] = useState("Common");
  const [selectedSymbol, setSelectedSymbol] = useState("");
  const [recentSymbols, setRecentSymbols] = useState<string[]>([]);

  const activeSymbols: SymbolSearchEntry[] = search
    ? filterSymbols(search)
    : (SYMBOL_CATEGORIES.find((category) => category.name === activeCategory)?.symbols.map(
        (symbol) => Object.assign({}, symbol, { category: activeCategory }),
      ) ?? []);

  const insertSymbol = (symbol: string) => {
    if (!symbol) {
      return;
    }
    setRecentSymbols((prev) =>
      [symbol, ...prev.filter((s) => s !== symbol)].slice(0, RECENT_LIMIT),
    );
    onInsert(symbol);
  };

  return (
    <Dialog open={isOpen} onOpenChange={handleOpenChange}>
      <DialogPortal>
        <DialogBackdrop className={DIALOG_BACKDROP_CLASS} />
        <DialogPopup className={DIALOG_POPUP_CLASS}>
          <DialogTitle className={DIALOG_TITLE_CLASS}>
            {t("dialogs.insertSymbol.title")}
          </DialogTitle>

          <div className={DIALOG_BODY_CLASS}>
            <input
              autoFocus
              value={search}
              onChange={(event) => setSearch(event.target.value)}
              onKeyDown={(event) => {
                if (event.key === "Escape") {
                  onClose();
                }
              }}
              placeholder={t("dialogs.insertSymbol.searchPlaceholder")}
              className={`${DIALOG_INPUT_CLASS} focus:border-primary w-full`}
            />

            {!search && (
              <div className="flex flex-wrap gap-0.5">
                {SYMBOL_CATEGORIES.map((category) => {
                  const active = activeCategory === category.name;
                  return (
                    <button
                      key={category.name}
                      type="button"
                      onClick={() => setActiveCategory(category.name)}
                      className={`rounded px-2 py-1 text-[11px] ${
                        active
                          ? "bg-accent text-accent-foreground font-semibold"
                          : "text-muted-foreground hover:bg-muted"
                      }`}
                    >
                      {t(category.nameKey)}
                    </button>
                  );
                })}
              </div>
            )}

            <div className="grid max-h-60 grid-cols-[repeat(auto-fill,minmax(2.25rem,1fr))] gap-0.5 overflow-y-auto rounded border p-1">
              {activeSymbols.map((symbol) => {
                const selected = selectedSymbol === symbol.char;
                return (
                  <button
                    key={symbol.char}
                    type="button"
                    title={symbol.name}
                    onClick={() => setSelectedSymbol(symbol.char)}
                    onDoubleClick={() => insertSymbol(symbol.char)}
                    className={`flex h-9 w-9 items-center justify-center rounded border text-lg ${
                      selected
                        ? "border-primary bg-primary/20"
                        : "hover:bg-muted border-transparent"
                    }`}
                  >
                    {symbol.char}
                  </button>
                );
              })}
              {activeSymbols.length === 0 && (
                <div className="text-muted-foreground col-span-full p-6 text-center text-[13px]">
                  {search
                    ? t("dialogs.insertSymbol.noResults", { query: search })
                    : t("dialogs.insertSymbol.noResultsEmpty")}
                </div>
              )}
            </div>

            {selectedSymbol && (
              <div className="bg-muted flex items-center gap-3 rounded px-3 py-2">
                <span className="text-3xl leading-none">{selectedSymbol}</span>
                <span className="text-muted-foreground font-mono text-xs">
                  {codePointLabel(selectedSymbol)}
                </span>
              </div>
            )}

            {recentSymbols.length > 0 && !search && (
              <div className="flex flex-wrap items-center gap-1">
                <span className="text-muted-foreground mr-1 text-[11px]">
                  {t("dialogs.insertSymbol.recent")}
                </span>
                {recentSymbols.map((symbol) => (
                  <button
                    key={symbol}
                    type="button"
                    title={codePointLabel(symbol)}
                    onClick={() => setSelectedSymbol(symbol)}
                    onDoubleClick={() => insertSymbol(symbol)}
                    className="hover:bg-muted flex h-7 w-7 items-center justify-center rounded border border-transparent text-sm"
                  >
                    {symbol}
                  </button>
                ))}
              </div>
            )}
          </div>

          <div className={DIALOG_FOOTER_CLASS}>
            <button type="button" className={DIALOG_SECONDARY_BUTTON_CLASS} onClick={onClose}>
              {t("common.cancel")}
            </button>
            <button
              type="button"
              className={DIALOG_PRIMARY_BUTTON_CLASS}
              disabled={!selectedSymbol}
              onClick={() => insertSymbol(selectedSymbol)}
            >
              {t("common.insert")}
            </button>
          </div>
        </DialogPopup>
      </DialogPortal>
    </Dialog>
  );
}
