// packages/vue/src/components/dialogs/SplitCellDialog.vue
<template>
  <FolioDialog
    :open="isOpen"
    aria-label="Split Cell"
    :style="{ minWidth: '360px', maxWidth: '520px', width: '100%' }"
    @close="$emit('close')"
    @keydown.enter="split"
  >
    <div class="dialog__header">Split Cell</div>
    <div class="dialog__body">
      <div class="grid">
        <label class="field">
          <span class="field__label">Columns</span>
          <input
            v-model.number="columns"
            class="field__input"
            :max="MAX_PARTS"
            :min="MIN_PARTS"
            type="number"
          />
        </label>
        <label class="field">
          <span class="field__label">Rows</span>
          <input
            v-model.number="rows"
            class="field__input"
            :max="MAX_PARTS"
            :min="MIN_PARTS"
            type="number"
          />
        </label>
      </div>
      <label class="check">
        <input v-model="mergeBeforeSplit" type="checkbox" />
        <span>Merge selected cells before splitting</span>
      </label>
    </div>
    <div class="dialog__footer">
      <button class="dialog__btn" @click="$emit('close')">Cancel</button>
      <button class="dialog__btn dialog__btn--primary" :disabled="!canSplit" @click="split">
        Split
      </button>
    </div>
  </FolioDialog>
</template>

<script setup lang="ts">
import { computed, ref, watch } from "vue";
import { useFolioUI } from "../../ui/folio-ui";

const { Dialog: FolioDialog } = useFolioUI();

export type SplitCellDialogData = {
  rows: number;
  columns: number;
  mergeBeforeSplit: boolean;
};

const MIN_PARTS = 1;
const MAX_PARTS = 63;

const props = withDefaults(
  defineProps<{
    isOpen: boolean;
    defaultRows?: number;
    defaultColumns?: number;
  }>(),
  { defaultRows: 1, defaultColumns: 2 },
);

const emit = defineEmits<{
  (e: "close"): void;
  (e: "split", data: SplitCellDialogData): void;
}>();

const rows = ref(props.defaultRows);
const columns = ref(props.defaultColumns);
const mergeBeforeSplit = ref(false);

const normalizedRows = computed(() => clampInteger(rows.value));
const normalizedColumns = computed(() => clampInteger(columns.value));
const canSplit = computed(() => normalizedRows.value > 1 || normalizedColumns.value > 1);

watch(
  () => props.isOpen,
  (open) => {
    if (!open) return;
    rows.value = props.defaultRows;
    columns.value = props.defaultColumns;
    mergeBeforeSplit.value = false;
  },
);

function split() {
  if (!canSplit.value) return;
  emit("split", {
    rows: normalizedRows.value,
    columns: normalizedColumns.value,
    mergeBeforeSplit: mergeBeforeSplit.value,
  });
  emit("close");
}

function clampInteger(value: number): number {
  return Math.min(MAX_PARTS, Math.max(MIN_PARTS, Math.trunc(value)));
}
</script>

<style scoped>
.dialog__header {
  padding: 16px 20px 12px;
  border-bottom: 1px solid var(--doc-border);
  font-size: 16px;
  font-weight: 600;
  color: var(--doc-text);
}
.dialog__body {
  padding: 16px 20px;
  display: flex;
  flex-direction: column;
  gap: 16px;
}
.dialog__footer {
  padding: 12px 20px 16px;
  border-top: 1px solid var(--doc-border);
  display: flex;
  justify-content: flex-end;
  gap: 8px;
}
.grid {
  display: grid;
  grid-template-columns: minmax(0, 1fr) minmax(0, 1fr);
  gap: 12px;
}
.field {
  display: flex;
  flex-direction: column;
  gap: 4px;
  min-width: 0;
}
.field__label,
.check {
  font-size: 13px;
  color: var(--doc-text-muted);
}
.field__input {
  border: 1px solid var(--doc-border);
  border-radius: 4px;
  background: var(--doc-surface);
  color: var(--doc-text);
  padding: 6px 8px;
  font-size: 13px;
  outline: none;
}
.check {
  display: flex;
  align-items: center;
  gap: 8px;
}
.dialog__btn {
  border: 1px solid var(--doc-border);
  border-radius: 4px;
  background: var(--doc-surface);
  color: var(--doc-text);
  padding: 6px 16px;
  font-size: 13px;
  cursor: pointer;
}
.dialog__btn--primary {
  border-color: var(--doc-primary);
  background: var(--doc-primary);
  color: white;
  font-weight: 600;
}
.dialog__btn:disabled {
  cursor: not-allowed;
  opacity: 0.5;
}
</style>

// packages/react/src/components/dialogs/SplitCellDialog.tsx
import { useEffect, useId, useState } from "react";

import { useFolioUI } from "../../ui/folio-ui";
import {
  DIALOG_BACKDROP_CLASS,
  DIALOG_BODY_CLASS,
  DIALOG_FOOTER_CLASS,
  DIALOG_INPUT_CLASS,
  DIALOG_LABEL_CLASS,
  DIALOG_POPUP_CLASS,
  DIALOG_PRIMARY_BUTTON_CLASS,
  DIALOG_SECONDARY_BUTTON_CLASS,
  DIALOG_TITLE_CLASS,
} from "./dialogChrome";

export type SplitCellDialogData = {
  rows: number;
  columns: number;
  mergeBeforeSplit: boolean;
};

export type SplitCellDialogProps = {
  isOpen: boolean;
  onClose: () => void;
  onSplit: (data: SplitCellDialogData) => void;
  defaultRows?: number;
  defaultColumns?: number;
};

const MIN_PARTS = 1;
const MAX_PARTS = 63;

export function SplitCellDialog({
  isOpen,
  onClose,
  onSplit,
  defaultRows = 1,
  defaultColumns = 2,
}: SplitCellDialogProps) {
  const {
    Root: Dialog,
    Portal: DialogPortal,
    Backdrop: DialogBackdrop,
    Popup: DialogPopup,
    Title: DialogTitle,
    Close: DialogClose,
  } = useFolioUI().Dialog;
  const id = useId();
  const [rows, setRows] = useState(defaultRows);
  const [columns, setColumns] = useState(defaultColumns);
  const [mergeBeforeSplit, setMergeBeforeSplit] = useState(false);

  useEffect(() => {
    if (!isOpen) {
      return;
    }
    setRows(defaultRows);
    setColumns(defaultColumns);
    setMergeBeforeSplit(false);
  }, [isOpen, defaultRows, defaultColumns]);

  const normalizedRows = clampInteger(rows);
  const normalizedColumns = clampInteger(columns);
  const canSplit = normalizedRows > 1 || normalizedColumns > 1;
  const fieldIds = {
    rows: `${id}-split-cell-rows`,
    columns: `${id}-split-cell-columns`,
    mergeBeforeSplit: `${id}-split-cell-merge-before-split`,
  };

  const handleSplit = () => {
    if (!canSplit) {
      return;
    }
    onSplit({ rows: normalizedRows, columns: normalizedColumns, mergeBeforeSplit });
    onClose();
  };

  return (
    <Dialog
      open={isOpen}
      onOpenChange={(open) => {
        if (!open) {
          onClose();
        }
      }}
    >
      <DialogPortal>
        <DialogBackdrop className={DIALOG_BACKDROP_CLASS} />
        <DialogPopup className={DIALOG_POPUP_CLASS}>
          <DialogTitle className={DIALOG_TITLE_CLASS}>Split Cell</DialogTitle>

          <div className={DIALOG_BODY_CLASS}>
            <div className="grid grid-cols-2 gap-3">
              <label className="flex flex-col gap-1" htmlFor={fieldIds.columns}>
                <span className={DIALOG_LABEL_CLASS}>Columns</span>
                <input
                  className={DIALOG_INPUT_CLASS}
                  id={fieldIds.columns}
                  max={MAX_PARTS}
                  min={MIN_PARTS}
                  onChange={(e) => setColumns(Number(e.target.value) || MIN_PARTS)}
                  type="number"
                  value={columns}
                />
              </label>
              <label className="flex flex-col gap-1" htmlFor={fieldIds.rows}>
                <span className={DIALOG_LABEL_CLASS}>Rows</span>
                <input
                  className={DIALOG_INPUT_CLASS}
                  id={fieldIds.rows}
                  max={MAX_PARTS}
                  min={MIN_PARTS}
                  onChange={(e) => setRows(Number(e.target.value) || MIN_PARTS)}
                  type="number"
                  value={rows}
                />
              </label>
            </div>

            <label className="flex items-center gap-2" htmlFor={fieldIds.mergeBeforeSplit}>
              <input
                checked={mergeBeforeSplit}
                id={fieldIds.mergeBeforeSplit}
                onChange={(e) => setMergeBeforeSplit(e.target.checked)}
                type="checkbox"
              />
              <span className={DIALOG_LABEL_CLASS}>Merge selected cells before splitting</span>
            </label>
          </div>

          <div className={DIALOG_FOOTER_CLASS}>
            <DialogClose className={DIALOG_SECONDARY_BUTTON_CLASS}>Cancel</DialogClose>
            <button
              className={DIALOG_PRIMARY_BUTTON_CLASS}
              disabled={!canSplit}
              onClick={handleSplit}
              type="button"
            >
              Split
            </button>
          </div>
        </DialogPopup>
      </DialogPortal>
    </Dialog>
  );
}

function clampInteger(value: number): number {
  return Math.min(MAX_PARTS, Math.max(MIN_PARTS, Math.trunc(value)));
}
