// packages/vue/src/components/dialogs/TablePropertiesDialog.vue
<!--
  Table Properties dialog — ported from the upstream docx-editor Vue adapter.
-->
<template>
  <FolioDialog
    :open="isOpen"
    :aria-label="t('dialogs.tableProperties.title')"
    :style="{ minWidth: '360px', maxWidth: '440px', width: '100%' }"
    @close="$emit('close')"
    @keydown.enter="apply"
  >
    <div class="tpd-dialog__header">{{ t("dialogs.tableProperties.title") }}</div>
    <div class="tpd-dialog__body">
      <div class="tpd-row">
        <label class="tpd-label">{{ t("dialogs.tableProperties.widthType") }}</label>
        <select v-model="widthType" class="tpd-select">
          <option value="auto">{{ t("dialogs.tableProperties.widthTypes.auto") }}</option>
          <option value="dxa">{{ t("dialogs.tableProperties.widthTypes.fixed") }}</option>
          <option value="pct">{{ t("dialogs.tableProperties.widthTypes.percentage") }}</option>
        </select>
      </div>
      <div v-if="widthType !== 'auto'" class="tpd-row">
        <label class="tpd-label">{{ t("dialogs.tableProperties.widthLabel") }}</label>
        <input
          v-model.number="width"
          type="number"
          class="tpd-input"
          :min="0"
          :step="widthType === 'pct' ? 5 : 100"
        />
        <span class="tpd-unit">{{
          widthType === "pct"
            ? t("dialogs.tableProperties.units.fiftiethsPercent")
            : t("dialogs.tableProperties.units.twips")
        }}</span>
      </div>
      <div class="tpd-row">
        <label class="tpd-label">{{ t("dialogs.tableProperties.alignmentLabel") }}</label>
        <select v-model="justification" class="tpd-select">
          <option v-for="value in TABLE_PROPERTY_JUSTIFICATIONS" :key="value" :value="value">
            {{ t(TABLE_JUSTIFICATION_LABEL_KEYS[value]) }}
          </option>
        </select>
      </div>
    </div>
    <div class="tpd-dialog__footer">
      <button class="tpd-btn" @click="$emit('close')">{{ t("common.cancel") }}</button>
      <button class="tpd-btn tpd-btn--primary" @click="apply">{{ t("common.apply") }}</button>
    </div>
  </FolioDialog>
</template>

<script setup lang="ts">
import { ref, watch } from "vue";
import {
  TABLE_PROPERTY_JUSTIFICATIONS,
  toTablePropertyJustification,
  type TablePropertiesCommand,
} from "@stll/folio-core/utils/tableOperations";
import { useTranslation } from "../../i18n";
import { useFolioUI } from "../../ui/folio-ui";

const { t } = useTranslation();

// Resolve Dialog from the FolioUI injection provider so a host override
// takes effect here too (previously a hand-rolled overlay + dialog div pair).
const { Dialog: FolioDialog } = useFolioUI();

export type TableProperties = TablePropertiesCommand;

const TABLE_JUSTIFICATION_LABEL_KEYS = {
  center: "dialogs.tableProperties.alignOptions.center",
  end: "dialogs.tableProperties.alignOptions.end",
  left: "dialogs.tableProperties.alignOptions.left",
  right: "dialogs.tableProperties.alignOptions.right",
  start: "dialogs.tableProperties.alignOptions.start",
} as const satisfies Record<
  NonNullable<TableProperties["justification"]>,
  `dialogs.tableProperties.alignOptions.${string}`
>;

const props = defineProps<{
  isOpen: boolean;
  currentProps?: TableProperties;
}>();

const emit = defineEmits<{
  (e: "close"): void;
  (e: "apply", props: TableProperties): void;
}>();

const width = ref(0);
const editableWidthType = (value: string): NonNullable<TableProperties["widthType"]> => {
  switch (value) {
    case "dxa":
    case "pct":
      return value;
    default:
      return "auto";
  }
};

const widthType = ref(editableWidthType(props.currentProps?.widthType ?? "auto"));
const justification = ref(toTablePropertyJustification(props.currentProps?.justification));

watch(
  () => props.isOpen,
  (open) => {
    if (open) {
      width.value = props.currentProps?.width ?? 0;
      widthType.value = editableWidthType(props.currentProps?.widthType ?? "auto");
      justification.value = toTablePropertyJustification(props.currentProps?.justification);
    }
  },
);

function apply() {
  const result: TableProperties =
    widthType.value === "auto"
      ? { justification: justification.value, width: null, widthType: "auto" }
      : { justification: justification.value, width: width.value, widthType: widthType.value };
  emit("apply", result);
  emit("close");
}
</script>

<style scoped>
/* The overlay + dialog box (background, border, shadow, centering) now come
   from the injected Dialog primitive (see the `<FolioDialog>` usage above);
   its width constraints are passed as an inline `:style` since Vue's scoped
   CSS can't reach into a child component's own template nodes. */
.tpd-dialog__header {
  padding: 16px 20px 12px;
  border-bottom: 1px solid var(--doc-border);
  font-size: 16px;
  font-weight: 600;
  color: var(--doc-text);
}
.tpd-dialog__body {
  padding: 16px 20px;
  display: flex;
  flex-direction: column;
  gap: 12px;
}
.tpd-dialog__footer {
  padding: 12px 20px 16px;
  border-top: 1px solid var(--doc-border);
  display: flex;
  justify-content: flex-end;
  gap: 8px;
}
.tpd-row {
  display: flex;
  align-items: center;
  gap: 12px;
}
.tpd-label {
  width: 80px;
  font-size: 13px;
  color: var(--doc-text-muted);
}
.tpd-input,
.tpd-select {
  flex: 1;
  padding: 6px 8px;
  border: 1px solid var(--doc-border-dark);
  border-radius: 4px;
  font-size: 13px;
}
.tpd-unit {
  font-size: 11px;
  color: var(--doc-text-subtle);
}
.tpd-btn {
  padding: 6px 16px;
  font-size: 13px;
  border: 1px solid var(--doc-border-dark);
  border-radius: 4px;
  cursor: pointer;
  background: var(--doc-surface);
}
.tpd-btn--primary {
  background: var(--doc-primary);
  color: var(--doc-on-primary);
  border-color: var(--doc-primary);
}
</style>

// packages/react/src/components/dialogs/TablePropertiesDialog.tsx
/**
 * Table Properties Dialog — width type, width value, alignment.
 */

import { useCallback, useEffect, useId, useState } from "react";
import { useTranslations } from "use-intl";

import {
  TABLE_PROPERTY_JUSTIFICATIONS,
  toTablePropertyJustification,
  type TablePropertiesCommand,
} from "@stll/folio-core/utils/tableOperations";

import { useFolioUI } from "../../ui/folio-ui";
import { useCloseOnDialogOpenChange } from "./dialogChrome";

export type TableProperties = TablePropertiesCommand;

export type TablePropertiesDialogProps = {
  isOpen: boolean;
  onClose: () => void;
  onApply: (props: TableProperties) => void;
  currentProps?: TableProperties;
};

const editableWidthType = (value: string): NonNullable<TableProperties["widthType"]> => {
  switch (value) {
    case "dxa":
    case "pct":
      return value;
    default:
      return "auto";
  }
};

const TABLE_JUSTIFICATION_LABEL_KEYS = {
  center: "dialogs.tableProperties.alignOptions.center",
  end: "dialogs.tableProperties.alignOptions.end",
  left: "dialogs.tableProperties.alignOptions.left",
  right: "dialogs.tableProperties.alignOptions.right",
  start: "dialogs.tableProperties.alignOptions.start",
} as const satisfies Record<
  NonNullable<TableProperties["justification"]>,
  `dialogs.tableProperties.alignOptions.${string}`
>;

export function TablePropertiesDialog({
  isOpen,
  onClose,
  onApply,
  currentProps,
}: TablePropertiesDialogProps) {
  const {
    Root: Dialog,
    Portal: DialogPortal,
    Backdrop: DialogBackdrop,
    Popup: DialogPopup,
    Title: DialogTitle,
    Close: DialogClose,
  } = useFolioUI().Dialog;
  const handleOpenChange = useCloseOnDialogOpenChange(onClose);
  const t = useTranslations("folio");
  const id = useId();
  const [width, setWidth] = useState(currentProps?.width ?? 0);
  const [widthType, setWidthType] = useState(editableWidthType(currentProps?.widthType ?? "auto"));
  const [justification, setJustification] = useState(
    toTablePropertyJustification(currentProps?.justification),
  );

  useEffect(() => {
    if (isOpen) {
      setWidth(currentProps?.width ?? 0);
      setWidthType(editableWidthType(currentProps?.widthType ?? "auto"));
      setJustification(toTablePropertyJustification(currentProps?.justification));
    }
  }, [isOpen, currentProps]);

  const handleApply = useCallback(() => {
    const props: TableProperties = {
      justification,
    };
    if (widthType === "auto") {
      props.width = null;
      props.widthType = "auto";
    } else {
      props.width = width;
      props.widthType = widthType;
    }
    onApply(props);
    onClose();
  }, [width, widthType, justification, onApply, onClose]);

  const labelCls = "w-20 text-muted-foreground text-[13px]";
  const inputCls =
    "border-input bg-background text-foreground flex-1 rounded border px-2 py-1.5 text-[13px] outline-none";
  const fieldIds = {
    widthType: `${id}-tp-width-type`,
    width: `${id}-tp-width`,
    align: `${id}-tp-align`,
  };

  return (
    <Dialog open={isOpen} onOpenChange={handleOpenChange}>
      <DialogPortal>
        <DialogBackdrop className="fixed inset-0 z-[10000] bg-black/50" />
        <DialogPopup className="bg-popover fixed start-1/2 top-1/2 z-[10001] w-full max-w-[440px] min-w-[360px] -translate-x-1/2 -translate-y-1/2 rounded-lg border shadow-xl">
          <DialogTitle className="border-b px-5 py-3 text-base font-semibold">
            {t("dialogs.tableProperties.title")}
          </DialogTitle>

          <div className="flex flex-col gap-3 px-5 py-4">
            <div className="flex items-center gap-3">
              <label className={labelCls} htmlFor={fieldIds.widthType}>
                {t("dialogs.tableProperties.widthType")}
              </label>
              <select
                className={inputCls}
                id={fieldIds.widthType}
                onChange={(e) => setWidthType(editableWidthType(e.target.value))}
                value={widthType}
              >
                <option value="auto">{t("dialogs.tableProperties.widthTypes.auto")}</option>
                <option value="dxa">{t("dialogs.tableProperties.widthTypes.fixed")}</option>
                <option value="pct">{t("dialogs.tableProperties.widthTypes.percentage")}</option>
              </select>
            </div>

            {widthType !== "auto" && (
              <div className="flex items-center gap-3">
                <label className={labelCls} htmlFor={fieldIds.width}>
                  {t("dialogs.tableProperties.widthLabel")}
                </label>
                <input
                  className={inputCls}
                  id={fieldIds.width}
                  min={0}
                  onChange={(e) => setWidth(Number(e.target.value) || 0)}
                  step={widthType === "pct" ? 5 : 100}
                  type="number"
                  value={width}
                />
                <span className="text-muted-foreground text-[11px]">
                  {widthType === "pct"
                    ? t("dialogs.tableProperties.units.fiftiethsPercent")
                    : t("dialogs.tableProperties.units.twips")}
                </span>
              </div>
            )}

            <div className="flex items-center gap-3">
              <label className={labelCls} htmlFor={fieldIds.align}>
                {t("dialogs.tableProperties.alignmentLabel")}
              </label>
              <select
                className={inputCls}
                id={fieldIds.align}
                onChange={(e) => setJustification(toTablePropertyJustification(e.target.value))}
                value={justification}
              >
                {TABLE_PROPERTY_JUSTIFICATIONS.map((value) => (
                  <option key={value} value={value}>
                    {t(TABLE_JUSTIFICATION_LABEL_KEYS[value])}
                  </option>
                ))}
              </select>
            </div>
          </div>

          <div className="flex justify-end gap-2 border-t px-5 py-3">
            <DialogClose className="border-input rounded border px-4 py-1.5 text-[13px]">
              {t("common.cancel")}
            </DialogClose>
            <button
              className="bg-primary text-primary-foreground rounded px-4 py-1.5 text-[13px] font-medium"
              onClick={handleApply}
              type="button"
            >
              {t("common.apply")}
            </button>
          </div>
        </DialogPopup>
      </DialogPortal>
    </Dialog>
  );
}
