// packages/vue/src/components/dialogs/WatermarkDialog.vue
<template>
  <FolioDialog
    :open="isOpen"
    aria-label="Watermark"
    :style="{ minWidth: '360px', maxWidth: '520px', width: '100%' }"
    @close="$emit('close')"
  >
    <div class="dialog__header">Watermark</div>
    <div class="dialog__body">
      <label class="field">
        <span class="field__label">Type</span>
        <select v-model="mode" class="field__input">
          <option value="text">Text watermark</option>
          <option value="picture">Picture watermark</option>
          <option value="none">No watermark</option>
        </select>
      </label>

      <div v-if="mode === 'text'" class="grid">
        <label class="field field--wide">
          <span class="field__label">Text</span>
          <input v-model="text" class="field__input" />
        </label>
        <label class="field">
          <span class="field__label">Font</span>
          <input v-model="font" class="field__input" />
        </label>
        <label class="field">
          <span class="field__label">Color</span>
          <input v-model="color" class="field__input field__input--color" type="color" />
        </label>
        <label class="field">
          <span class="field__label">Opacity</span>
          <input
            v-model.number="opacityPercent"
            class="field__input"
            max="100"
            min="0"
            type="number"
          />
        </label>
        <label class="check">
          <input v-model="diagonal" type="checkbox" />
          <span>Diagonal</span>
        </label>
      </div>

      <div v-if="mode === 'picture'" class="grid">
        <label class="field field--wide">
          <span class="field__label">Header image relationship id</span>
          <input v-model="imageRId" class="field__input" placeholder="rId12" />
        </label>
        <label class="field field--wide">
          <span class="field__label">Image target</span>
          <input
            v-model="imageTarget"
            :aria-invalid="imageTargetError.length > 0"
            class="field__input"
            placeholder="word/media/image1.png"
          />
          <span v-if="imageTargetError.length > 0" class="field__error">{{
            imageTargetError
          }}</span>
        </label>
        <label class="field">
          <span class="field__label">Scale</span>
          <input
            v-model.number="scalePercent"
            class="field__input"
            max="300"
            min="1"
            type="number"
          />
        </label>
        <label class="check">
          <input v-model="washout" type="checkbox" />
          <span>Washout</span>
        </label>
        <label class="check field--wide">
          <input v-model="imageTargetExternal" type="checkbox" />
          <span>Target is an external URL</span>
        </label>
      </div>
    </div>
    <div class="dialog__footer">
      <button class="dialog__btn" @click="$emit('close')">Cancel</button>
      <button class="dialog__btn dialog__btn--primary" :disabled="!canApply" @click="apply">
        Apply
      </button>
    </div>
  </FolioDialog>
</template>

<script setup lang="ts">
import { computed, ref, watch } from "vue";
import { isAllowedExternalWatermarkImageUrl, type Watermark } from "@stll/folio-core/watermark";
import { useFolioUI } from "../../ui/folio-ui";

const { Dialog: FolioDialog } = useFolioUI();

type WatermarkMode = "none" | "text" | "picture";

const props = defineProps<{
  isOpen: boolean;
  currentWatermark?: Watermark | undefined;
}>();

const emit = defineEmits<{
  (e: "close"): void;
  (e: "apply", watermark: Watermark | undefined): void;
}>();

const DEFAULT_TEXT_COLOR = "#C0C0C0";

const mode = ref<WatermarkMode>("text");
const text = ref("CONFIDENTIAL");
const font = ref("Calibri");
const color = ref(DEFAULT_TEXT_COLOR);
const diagonal = ref(true);
const opacityPercent = ref(50);
const imageRId = ref("");
const imageTarget = ref("");
const imageTargetExternal = ref(false);
const scalePercent = ref(100);
const washout = ref(true);

// An external target becomes a `TargetMode="External"` relationship in the
// saved package verbatim (see `docx/rezip.ts`); restrict it to http(s) so a
// `file:` URL or UNC path can't ride along in the exported `.docx`.
const imageTargetError = computed(() =>
  mode.value === "picture" && imageTargetExternal.value && imageTarget.value.trim().length > 0
    ? getExternalImageTargetError(imageTarget.value.trim())
    : "",
);

const canApply = computed(
  () =>
    mode.value === "none" ||
    (mode.value === "text" && text.value.trim().length > 0) ||
    (mode.value === "picture" &&
      imageRId.value.trim().length > 0 &&
      imageTargetError.value.length === 0),
);

watch(
  [() => props.isOpen, () => props.currentWatermark],
  ([open, watermark]) => {
    if (!open) return;
    if (!watermark) {
      mode.value = "text";
      text.value = "CONFIDENTIAL";
      font.value = "Calibri";
      color.value = DEFAULT_TEXT_COLOR;
      diagonal.value = true;
      opacityPercent.value = 50;
      imageRId.value = "";
      imageTarget.value = "";
      imageTargetExternal.value = false;
      scalePercent.value = 100;
      washout.value = true;
      return;
    }
    mode.value = watermark.kind;
    if (watermark.kind === "text") {
      text.value = watermark.text;
      font.value = watermark.font ?? "Calibri";
      color.value = toColorInputValue(watermark.color);
      diagonal.value = watermark.diagonal ?? true;
      opacityPercent.value = Math.round((watermark.opacity ?? 0.5) * 100);
      return;
    }
    imageRId.value = watermark.imageRId;
    imageTarget.value = watermark.imageTarget ?? "";
    imageTargetExternal.value = watermark.imageTargetExternal ?? false;
    scalePercent.value = Math.round((watermark.scale ?? 1) * 100);
    washout.value = watermark.washout ?? true;
  },
  { immediate: true },
);

function apply() {
  if (!canApply.value) return;
  if (mode.value === "none") {
    emit("apply", undefined);
    emit("close");
    return;
  }
  if (mode.value === "text") {
    emit("apply", {
      kind: "text",
      text: text.value.trim(),
      ...(font.value.trim() ? { font: font.value.trim() } : {}),
      color: stripHash(color.value),
      diagonal: diagonal.value,
      opacity: clampPercent(opacityPercent.value) / 100,
    });
    emit("close");
    return;
  }
  emit("apply", {
    kind: "picture",
    imageRId: imageRId.value.trim(),
    ...(imageTarget.value.trim() ? { imageTarget: imageTarget.value.trim() } : {}),
    ...(imageTarget.value.trim() ? { imageTargetExternal: imageTargetExternal.value } : {}),
    scale: clampScalePercent(scalePercent.value) / 100,
    washout: washout.value,
  });
  emit("close");
}

function clampPercent(value: number): number {
  return Math.min(100, Math.max(0, value));
}

function clampScalePercent(value: number): number {
  return Math.min(300, Math.max(1, value));
}

function stripHash(value: string): string {
  return value.startsWith("#") ? value.slice(1) : value;
}

function getExternalImageTargetError(value: string): string {
  return isAllowedExternalWatermarkImageUrl(value) ? "" : "Use a web address (http/https).";
}

function toColorInputValue(value: string | undefined): string {
  if (!value || value === "auto") return DEFAULT_TEXT_COLOR;
  return value.startsWith("#") ? value : `#${value}`;
}
</script>

<style scoped>
.dialog__header {
  padding: 16px 20px 12px;
  border-bottom: 1px solid var(--doc-border);
  font-size: 16px;
  font-weight: 600;
  color: var(--doc-text);
}
.dialog__body {
  padding: 16px 20px;
  display: flex;
  flex-direction: column;
  gap: 16px;
}
.dialog__footer {
  padding: 12px 20px 16px;
  border-top: 1px solid var(--doc-border);
  display: flex;
  justify-content: flex-end;
  gap: 8px;
}
.grid {
  display: grid;
  grid-template-columns: minmax(0, 1fr) minmax(0, 1fr);
  gap: 12px;
}
.field {
  display: flex;
  flex-direction: column;
  gap: 4px;
  min-width: 0;
}
.field--wide {
  grid-column: 1 / -1;
}
.field__label,
.check {
  font-size: 13px;
  color: var(--doc-text-muted);
}
.field__input {
  border: 1px solid var(--doc-border);
  border-radius: 4px;
  background: var(--doc-surface);
  color: var(--doc-text);
  padding: 6px 8px;
  font-size: 13px;
  outline: none;
}
.field__input--color {
  min-height: 34px;
  padding: 2px;
}
.field__error {
  font-size: 12px;
  color: var(--doc-error);
}
.check {
  display: flex;
  align-items: center;
  gap: 8px;
  padding-top: 22px;
}
.dialog__btn {
  border: 1px solid var(--doc-border);
  border-radius: 4px;
  background: var(--doc-surface);
  color: var(--doc-text);
  padding: 6px 16px;
  font-size: 13px;
  cursor: pointer;
}
.dialog__btn--primary {
  border-color: var(--doc-primary);
  background: var(--doc-primary);
  color: white;
  font-weight: 600;
}
.dialog__btn:disabled {
  cursor: not-allowed;
  opacity: 0.5;
}
</style>

// packages/react/src/components/dialogs/WatermarkDialog.tsx
import { useEffect, useId, useState } from "react";
import { useTranslations } from "use-intl";

import { isAllowedExternalWatermarkImageUrl, type Watermark } from "@stll/folio-core/watermark";
import { useFolioUI } from "../../ui/folio-ui";
import {
  DIALOG_BACKDROP_CLASS,
  DIALOG_BODY_CLASS,
  DIALOG_FOOTER_CLASS,
  DIALOG_INPUT_CLASS,
  DIALOG_LABEL_CLASS,
  DIALOG_POPUP_CLASS,
  DIALOG_PRIMARY_BUTTON_CLASS,
  DIALOG_SECONDARY_BUTTON_CLASS,
  DIALOG_TITLE_CLASS,
  useCloseOnDialogOpenChange,
} from "./dialogChrome";

export type WatermarkDialogProps = {
  isOpen: boolean;
  onClose: () => void;
  onApply: (watermark: Watermark | undefined) => void;
  currentWatermark?: Watermark;
};

type WatermarkMode = "none" | "text" | "picture";

const DEFAULT_TEXT_COLOR = "#C0C0C0";

export function WatermarkDialog({
  isOpen,
  onClose,
  onApply,
  currentWatermark,
}: WatermarkDialogProps) {
  const {
    Root: Dialog,
    Portal: DialogPortal,
    Backdrop: DialogBackdrop,
    Popup: DialogPopup,
    Title: DialogTitle,
    Close: DialogClose,
  } = useFolioUI().Dialog;
  const handleOpenChange = useCloseOnDialogOpenChange(onClose);
  const t = useTranslations("folio");
  const id = useId();
  const [mode, setMode] = useState<WatermarkMode>("text");
  const [text, setText] = useState("CONFIDENTIAL");
  const [font, setFont] = useState("Calibri");
  const [color, setColor] = useState(DEFAULT_TEXT_COLOR);
  const [diagonal, setDiagonal] = useState(true);
  const [opacityPercent, setOpacityPercent] = useState(50);
  const [imageRId, setImageRId] = useState("");
  const [imageTarget, setImageTarget] = useState("");
  const [imageTargetExternal, setImageTargetExternal] = useState(false);
  const [scalePercent, setScalePercent] = useState(100);
  const [washout, setWashout] = useState(true);

  useEffect(() => {
    if (!isOpen) {
      return;
    }
    if (!currentWatermark) {
      setMode("text");
      setText("CONFIDENTIAL");
      setFont("Calibri");
      setColor(DEFAULT_TEXT_COLOR);
      setDiagonal(true);
      setOpacityPercent(50);
      setImageRId("");
      setImageTarget("");
      setImageTargetExternal(false);
      setScalePercent(100);
      setWashout(true);
      return;
    }
    setMode(currentWatermark.kind);
    if (currentWatermark.kind === "text") {
      setText(currentWatermark.text);
      setFont(currentWatermark.font ?? "Calibri");
      setColor(toColorInputValue(currentWatermark.color));
      setDiagonal(currentWatermark.diagonal ?? true);
      setOpacityPercent(Math.round((currentWatermark.opacity ?? 0.5) * 100));
      return;
    }
    setImageRId(currentWatermark.imageRId);
    setImageTarget(currentWatermark.imageTarget ?? "");
    setImageTargetExternal(currentWatermark.imageTargetExternal ?? false);
    setScalePercent(Math.round((currentWatermark.scale ?? 1) * 100));
    setWashout(currentWatermark.washout ?? true);
  }, [isOpen, currentWatermark]);

  const fieldIds = {
    mode: `${id}-watermark-mode`,
    text: `${id}-watermark-text`,
    font: `${id}-watermark-font`,
    color: `${id}-watermark-color`,
    diagonal: `${id}-watermark-diagonal`,
    opacity: `${id}-watermark-opacity`,
    imageRId: `${id}-watermark-image-rid`,
    imageTarget: `${id}-watermark-image-target`,
    imageTargetExternal: `${id}-watermark-image-external`,
    scale: `${id}-watermark-scale`,
    washout: `${id}-watermark-washout`,
  };

  // An external target becomes a `TargetMode="External"` relationship in the
  // saved package verbatim (see `docx/rezip.ts`); restrict it to http(s) so a
  // `file:` URL or UNC path can't ride along in the exported `.docx`.
  const imageTargetError =
    mode === "picture" && imageTargetExternal && imageTarget.trim().length > 0
      ? getExternalImageTargetError(imageTarget.trim())
      : "";

  const canApply =
    mode === "none" ||
    (mode === "text" && text.trim().length > 0) ||
    (mode === "picture" && imageRId.trim().length > 0 && imageTargetError.length === 0);

  const handleApply = () => {
    if (!canApply) {
      return;
    }
    if (mode === "none") {
      onApply(undefined);
      onClose();
      return;
    }
    if (mode === "text") {
      onApply({
        kind: "text",
        text: text.trim(),
        ...(font.trim() ? { font: font.trim() } : {}),
        color: stripHash(color),
        diagonal,
        opacity: clampPercent(opacityPercent) / 100,
      });
      onClose();
      return;
    }
    onApply({
      kind: "picture",
      imageRId: imageRId.trim(),
      ...(imageTarget.trim() ? { imageTarget: imageTarget.trim() } : {}),
      ...(imageTarget.trim() ? { imageTargetExternal } : {}),
      scale: clampScalePercent(scalePercent) / 100,
      washout,
    });
    onClose();
  };

  return (
    <Dialog open={isOpen} onOpenChange={handleOpenChange}>
      <DialogPortal>
        <DialogBackdrop className={DIALOG_BACKDROP_CLASS} />
        <DialogPopup className={DIALOG_POPUP_CLASS}>
          <DialogTitle className={DIALOG_TITLE_CLASS}>{t("dialogs.watermark.title")}</DialogTitle>

          <div className={DIALOG_BODY_CLASS}>
            <label className="flex flex-col gap-1" htmlFor={fieldIds.mode}>
              <span className={DIALOG_LABEL_CLASS}>{t("dialogs.watermark.type")}</span>
              <select
                className={DIALOG_INPUT_CLASS}
                id={fieldIds.mode}
                onChange={(e) => setMode(toWatermarkMode(e.target.value))}
                value={mode}
              >
                <option value="text">{t("dialogs.watermark.textWatermark")}</option>
                <option value="picture">{t("dialogs.watermark.pictureWatermark")}</option>
                <option value="none">{t("dialogs.watermark.noWatermark")}</option>
              </select>
            </label>

            {mode === "text" && (
              <div className="grid grid-cols-2 gap-3">
                <label className="col-span-2 flex flex-col gap-1" htmlFor={fieldIds.text}>
                  <span className={DIALOG_LABEL_CLASS}>{t("dialogs.watermark.text")}</span>
                  <input
                    className={DIALOG_INPUT_CLASS}
                    id={fieldIds.text}
                    onChange={(e) => setText(e.target.value)}
                    value={text}
                  />
                </label>
                <label className="flex flex-col gap-1" htmlFor={fieldIds.font}>
                  <span className={DIALOG_LABEL_CLASS}>{t("dialogs.watermark.font")}</span>
                  <input
                    className={DIALOG_INPUT_CLASS}
                    id={fieldIds.font}
                    onChange={(e) => setFont(e.target.value)}
                    value={font}
                  />
                </label>
                <label className="flex flex-col gap-1" htmlFor={fieldIds.color}>
                  <span className={DIALOG_LABEL_CLASS}>{t("dialogs.watermark.color")}</span>
                  <input
                    className={`${DIALOG_INPUT_CLASS} h-[34px]`}
                    id={fieldIds.color}
                    onChange={(e) => setColor(e.target.value)}
                    type="color"
                    value={color}
                  />
                </label>
                <label className="flex flex-col gap-1" htmlFor={fieldIds.opacity}>
                  <span className={DIALOG_LABEL_CLASS}>{t("dialogs.watermark.opacity")}</span>
                  <input
                    className={DIALOG_INPUT_CLASS}
                    id={fieldIds.opacity}
                    max={100}
                    min={0}
                    onChange={(e) => setOpacityPercent(Number(e.target.value) || 0)}
                    type="number"
                    value={opacityPercent}
                  />
                </label>
                <label className="flex items-center gap-2 pt-6" htmlFor={fieldIds.diagonal}>
                  <input
                    checked={diagonal}
                    id={fieldIds.diagonal}
                    onChange={(e) => setDiagonal(e.target.checked)}
                    type="checkbox"
                  />
                  <span className={DIALOG_LABEL_CLASS}>{t("dialogs.watermark.diagonal")}</span>
                </label>
              </div>
            )}

            {mode === "picture" && (
              <div className="grid grid-cols-2 gap-3">
                <label className="col-span-2 flex flex-col gap-1" htmlFor={fieldIds.imageRId}>
                  <span className={DIALOG_LABEL_CLASS}>
                    {t("dialogs.watermark.imageRelationshipId")}
                  </span>
                  <input
                    className={DIALOG_INPUT_CLASS}
                    id={fieldIds.imageRId}
                    onChange={(e) => setImageRId(e.target.value)}
                    placeholder="rId12"
                    value={imageRId}
                  />
                </label>
                <label className="col-span-2 flex flex-col gap-1" htmlFor={fieldIds.imageTarget}>
                  <span className={DIALOG_LABEL_CLASS}>{t("dialogs.watermark.imageTarget")}</span>
                  <input
                    aria-invalid={imageTargetError.length > 0}
                    className={DIALOG_INPUT_CLASS}
                    id={fieldIds.imageTarget}
                    onChange={(e) => setImageTarget(e.target.value)}
                    placeholder="word/media/image1.png"
                    value={imageTarget}
                  />
                  {imageTargetError.length > 0 && (
                    <span className="text-destructive text-xs">{imageTargetError}</span>
                  )}
                </label>
                <label className="flex flex-col gap-1" htmlFor={fieldIds.scale}>
                  <span className={DIALOG_LABEL_CLASS}>{t("dialogs.watermark.scale")}</span>
                  <input
                    className={DIALOG_INPUT_CLASS}
                    id={fieldIds.scale}
                    max={300}
                    min={1}
                    onChange={(e) => setScalePercent(Number(e.target.value) || 1)}
                    type="number"
                    value={scalePercent}
                  />
                </label>
                <label className="flex items-center gap-2 pt-6" htmlFor={fieldIds.washout}>
                  <input
                    checked={washout}
                    id={fieldIds.washout}
                    onChange={(e) => setWashout(e.target.checked)}
                    type="checkbox"
                  />
                  <span className={DIALOG_LABEL_CLASS}>{t("dialogs.watermark.washout")}</span>
                </label>
                <label
                  className="col-span-2 flex items-center gap-2"
                  htmlFor={fieldIds.imageTargetExternal}
                >
                  <input
                    checked={imageTargetExternal}
                    id={fieldIds.imageTargetExternal}
                    onChange={(e) => setImageTargetExternal(e.target.checked)}
                    type="checkbox"
                  />
                  <span className={DIALOG_LABEL_CLASS}>
                    {t("dialogs.watermark.targetIsExternalUrl")}
                  </span>
                </label>
              </div>
            )}
          </div>

          <div className={DIALOG_FOOTER_CLASS}>
            <DialogClose className={DIALOG_SECONDARY_BUTTON_CLASS}>
              {t("common.cancel")}
            </DialogClose>
            <button
              className={DIALOG_PRIMARY_BUTTON_CLASS}
              disabled={!canApply}
              onClick={handleApply}
              type="button"
            >
              {t("common.apply")}
            </button>
          </div>
        </DialogPopup>
      </DialogPortal>
    </Dialog>
  );
}

function toWatermarkMode(value: string): WatermarkMode {
  if (value === "none" || value === "picture" || value === "text") {
    return value;
  }
  return "text";
}

function clampPercent(value: number): number {
  return Math.min(100, Math.max(0, value));
}

function clampScalePercent(value: number): number {
  return Math.min(300, Math.max(1, value));
}

function stripHash(value: string): string {
  return value.startsWith("#") ? value.slice(1) : value;
}

/** Mirrors `HyperlinkDialog.tsx`'s `getUrlError` — a plain-English, untranslated
 * field-level validation message (existing convention for this kind of inline
 * error in this dialog family). */
function getExternalImageTargetError(value: string): string {
  return isAllowedExternalWatermarkImageUrl(value) ? "" : "Use a web address (http/https).";
}

function toColorInputValue(value: string | undefined): string {
  if (!value || value === "auto") {
    return DEFAULT_TEXT_COLOR;
  }
  return value.startsWith("#") ? value : `#${value}`;
}
