// packages/react/src/components/dialogs/ImagePositionDialog.tsx
/**
 * Image Position Dialog
 *
 * Modal for editing image positioning settings:
 * - Horizontal: alignment or offset, relative to page/column/margin/paragraph
 * - Vertical: alignment or offset, relative to page/margin/paragraph/line
 * - Distance from text (top/bottom/left/right)
 */

import { useEffect, useId, useState } from "react";
import { useTranslations } from "use-intl";

import { useFolioUI } from "../../ui/folio-ui";
import { useCloseOnDialogOpenChange } from "./dialogChrome";

// ============================================================================
// TYPES
// ============================================================================

export type ImagePositionData = {
  horizontal?: {
    relativeTo?: string;
    posOffset?: number;
    align?: string;
  };
  vertical?: {
    relativeTo?: string;
    posOffset?: number;
    align?: string;
  };
  distTop?: number;
  distBottom?: number;
  distLeft?: number;
  distRight?: number;
};

export type ImagePositionDialogProps = {
  isOpen: boolean;
  onClose: () => void;
  onApply: (data: ImagePositionData) => void;
  currentData?: ImagePositionData;
};

// ============================================================================
// COMPONENT
// ============================================================================

export function ImagePositionDialog({
  isOpen,
  onClose,
  onApply,
  currentData,
}: ImagePositionDialogProps) {
  const {
    Root: Dialog,
    Portal: DialogPortal,
    Backdrop: DialogBackdrop,
    Popup: DialogPopup,
    Title: DialogTitle,
    Close: DialogClose,
  } = useFolioUI().Dialog;
  const handleOpenChange = useCloseOnDialogOpenChange(onClose);
  const t = useTranslations("folio");
  const id = useId();
  const [hMode, setHMode] = useState<"align" | "offset">("align");
  const [hAlign, setHAlign] = useState("center");
  const [hRelativeTo, setHRelativeTo] = useState("column");
  const [hOffset, setHOffset] = useState(0);

  const [vMode, setVMode] = useState<"align" | "offset">("align");
  const [vAlign, setVAlign] = useState("top");
  const [vRelativeTo, setVRelativeTo] = useState("paragraph");
  const [vOffset, setVOffset] = useState(0);

  const [distTop, setDistTop] = useState(0);
  const [distBottom, setDistBottom] = useState(0);
  const [distLeft, setDistLeft] = useState(0);
  const [distRight, setDistRight] = useState(0);

  useEffect(() => {
    if (!isOpen) {
      return;
    }
    const h = currentData?.horizontal;
    const v = currentData?.vertical;
    if (h?.align) {
      setHMode("align");
      setHAlign(h.align);
    } else if (h?.posOffset !== undefined) {
      setHMode("offset");
      setHOffset(h.posOffset);
    }
    if (h?.relativeTo) {
      setHRelativeTo(h.relativeTo);
    }

    if (v?.align) {
      setVMode("align");
      setVAlign(v.align);
    } else if (v?.posOffset !== undefined) {
      setVMode("offset");
      setVOffset(v.posOffset);
    }
    if (v?.relativeTo) {
      setVRelativeTo(v.relativeTo);
    }

    setDistTop(currentData?.distTop ?? 0);
    setDistBottom(currentData?.distBottom ?? 0);
    setDistLeft(currentData?.distLeft ?? 0);
    setDistRight(currentData?.distRight ?? 0);
  }, [isOpen, currentData]);

  const handleApply = () => {
    const data: ImagePositionData = {};
    data.horizontal = {
      relativeTo: hRelativeTo,
      ...(hMode === "align" ? { align: hAlign } : { posOffset: hOffset }),
    };
    data.vertical = {
      relativeTo: vRelativeTo,
      ...(vMode === "align" ? { align: vAlign } : { posOffset: vOffset }),
    };
    data.distTop = distTop;
    data.distBottom = distBottom;
    data.distLeft = distLeft;
    data.distRight = distRight;
    onApply(data);
    onClose();
  };

  const labelCls = "w-[75px] text-muted-foreground text-xs";
  const inputCls =
    "border-input bg-background text-foreground flex-1 rounded border px-1.5 py-1 text-xs outline-none";
  const sectionLabelCls = "text-foreground text-[13px] font-semibold";
  const distLabelCls = "w-[45px] text-muted-foreground text-xs";
  const fieldIds = {
    hMode: `${id}-img-pos-h-mode`,
    hAlign: `${id}-img-pos-h-align`,
    hOffset: `${id}-img-pos-h-offset`,
    hRelativeTo: `${id}-img-pos-h-rel`,
    vMode: `${id}-img-pos-v-mode`,
    vAlign: `${id}-img-pos-v-align`,
    vOffset: `${id}-img-pos-v-offset`,
    vRelativeTo: `${id}-img-pos-v-rel`,
    distTop: `${id}-img-pos-dist-top`,
    distBottom: `${id}-img-pos-dist-bottom`,
    distLeft: `${id}-img-pos-dist-left`,
    distRight: `${id}-img-pos-dist-right`,
  };

  return (
    <Dialog open={isOpen} onOpenChange={handleOpenChange}>
      <DialogPortal>
        <DialogBackdrop className="fixed inset-0 z-[10000] bg-black/50" />
        <DialogPopup className="bg-popover fixed start-1/2 top-1/2 z-[10001] w-full max-w-[480px] min-w-[400px] -translate-x-1/2 -translate-y-1/2 rounded-lg border shadow-xl">
          <DialogTitle className="border-b px-5 py-3 text-base font-semibold">
            {t("dialogs.imagePosition.title")}
          </DialogTitle>

          <div className="flex flex-col gap-4 px-5 py-4">
            {/* Horizontal positioning */}
            <div className="flex flex-col gap-2">
              <div className={sectionLabelCls}>{t("dialogs.imagePosition.horizontal")}</div>
              <div className="flex items-center gap-2">
                <label className={labelCls} htmlFor={fieldIds.hMode}>
                  {t("dialogs.imagePosition.position")}
                </label>
                <select
                  className={inputCls}
                  id={fieldIds.hMode}
                  value={hMode}
                  onChange={(e) => setHMode(e.target.value as "align" | "offset")}
                >
                  <option value="align">{t("dialogs.imagePosition.alignment")}</option>
                  <option value="offset">{t("dialogs.imagePosition.offset")}</option>
                </select>
              </div>
              {hMode === "align" ? (
                <div className="flex items-center gap-2">
                  <label className={labelCls} htmlFor={fieldIds.hAlign}>
                    {t("dialogs.imagePosition.align")}
                  </label>
                  <select
                    className={inputCls}
                    id={fieldIds.hAlign}
                    value={hAlign}
                    onChange={(e) => setHAlign(e.target.value)}
                  >
                    <option value="left">{t("dialogs.imagePosition.alignOptions.left")}</option>
                    <option value="center">{t("dialogs.imagePosition.alignOptions.center")}</option>
                    <option value="right">{t("dialogs.imagePosition.alignOptions.right")}</option>
                  </select>
                </div>
              ) : (
                <div className="flex items-center gap-2">
                  <label className={labelCls} htmlFor={fieldIds.hOffset}>
                    {t("dialogs.imagePosition.offsetPx")}
                  </label>
                  <input
                    className={inputCls}
                    id={fieldIds.hOffset}
                    type="number"
                    value={hOffset}
                    onChange={(e) => setHOffset(Number(e.target.value) || 0)}
                  />
                </div>
              )}
              <div className="flex items-center gap-2">
                <label className={labelCls} htmlFor={fieldIds.hRelativeTo}>
                  {t("dialogs.imagePosition.relativeTo")}
                </label>
                <select
                  className={inputCls}
                  id={fieldIds.hRelativeTo}
                  value={hRelativeTo}
                  onChange={(e) => setHRelativeTo(e.target.value)}
                >
                  <option value="page">{t("dialogs.imagePosition.relativeOptions.page")}</option>
                  <option value="column">
                    {t("dialogs.imagePosition.relativeOptions.column")}
                  </option>
                  <option value="margin">
                    {t("dialogs.imagePosition.relativeOptions.margin")}
                  </option>
                  <option value="character">
                    {t("dialogs.imagePosition.relativeOptions.character")}
                  </option>
                </select>
              </div>
            </div>

            {/* Vertical positioning */}
            <div className="flex flex-col gap-2">
              <div className={sectionLabelCls}>{t("dialogs.imagePosition.vertical")}</div>
              <div className="flex items-center gap-2">
                <label className={labelCls} htmlFor={fieldIds.vMode}>
                  {t("dialogs.imagePosition.position")}
                </label>
                <select
                  className={inputCls}
                  id={fieldIds.vMode}
                  value={vMode}
                  onChange={(e) => setVMode(e.target.value as "align" | "offset")}
                >
                  <option value="align">{t("dialogs.imagePosition.alignment")}</option>
                  <option value="offset">{t("dialogs.imagePosition.offset")}</option>
                </select>
              </div>
              {vMode === "align" ? (
                <div className="flex items-center gap-2">
                  <label className={labelCls} htmlFor={fieldIds.vAlign}>
                    {t("dialogs.imagePosition.align")}
                  </label>
                  <select
                    className={inputCls}
                    id={fieldIds.vAlign}
                    value={vAlign}
                    onChange={(e) => setVAlign(e.target.value)}
                  >
                    <option value="top">{t("dialogs.imagePosition.alignOptions.top")}</option>
                    <option value="center">{t("dialogs.imagePosition.alignOptions.center")}</option>
                    <option value="bottom">{t("dialogs.imagePosition.alignOptions.bottom")}</option>
                  </select>
                </div>
              ) : (
                <div className="flex items-center gap-2">
                  <label className={labelCls} htmlFor={fieldIds.vOffset}>
                    {t("dialogs.imagePosition.offsetPx")}
                  </label>
                  <input
                    className={inputCls}
                    id={fieldIds.vOffset}
                    type="number"
                    value={vOffset}
                    onChange={(e) => setVOffset(Number(e.target.value) || 0)}
                  />
                </div>
              )}
              <div className="flex items-center gap-2">
                <label className={labelCls} htmlFor={fieldIds.vRelativeTo}>
                  {t("dialogs.imagePosition.relativeTo")}
                </label>
                <select
                  className={inputCls}
                  id={fieldIds.vRelativeTo}
                  value={vRelativeTo}
                  onChange={(e) => setVRelativeTo(e.target.value)}
                >
                  <option value="page">{t("dialogs.imagePosition.relativeOptions.page")}</option>
                  <option value="margin">
                    {t("dialogs.imagePosition.relativeOptions.margin")}
                  </option>
                  <option value="paragraph">
                    {t("dialogs.imagePosition.relativeOptions.paragraph")}
                  </option>
                  <option value="line">{t("dialogs.imagePosition.relativeOptions.line")}</option>
                </select>
              </div>
            </div>

            {/* Distance from text */}
            <div className="flex flex-col gap-2">
              <div className={sectionLabelCls}>{t("dialogs.imagePosition.distanceFromText")}</div>
              <div className="grid grid-cols-2 gap-2">
                <div className="flex items-center gap-2">
                  <label className={distLabelCls} htmlFor={fieldIds.distTop}>
                    {t("dialogs.imagePosition.alignOptions.top")}
                  </label>
                  <input
                    className={inputCls}
                    id={fieldIds.distTop}
                    min={0}
                    type="number"
                    value={distTop}
                    onChange={(e) => setDistTop(Number(e.target.value) || 0)}
                  />
                </div>
                <div className="flex items-center gap-2">
                  <label className={distLabelCls} htmlFor={fieldIds.distBottom}>
                    {t("dialogs.imagePosition.alignOptions.bottom")}
                  </label>
                  <input
                    className={inputCls}
                    id={fieldIds.distBottom}
                    min={0}
                    type="number"
                    value={distBottom}
                    onChange={(e) => setDistBottom(Number(e.target.value) || 0)}
                  />
                </div>
                <div className="flex items-center gap-2">
                  <label className={distLabelCls} htmlFor={fieldIds.distLeft}>
                    {t("dialogs.imagePosition.alignOptions.left")}
                  </label>
                  <input
                    className={inputCls}
                    id={fieldIds.distLeft}
                    min={0}
                    type="number"
                    value={distLeft}
                    onChange={(e) => setDistLeft(Number(e.target.value) || 0)}
                  />
                </div>
                <div className="flex items-center gap-2">
                  <label className={distLabelCls} htmlFor={fieldIds.distRight}>
                    {t("dialogs.imagePosition.alignOptions.right")}
                  </label>
                  <input
                    className={inputCls}
                    id={fieldIds.distRight}
                    min={0}
                    type="number"
                    value={distRight}
                    onChange={(e) => setDistRight(Number(e.target.value) || 0)}
                  />
                </div>
              </div>
            </div>
          </div>

          <div className="flex justify-end gap-2 border-t px-5 py-3">
            <DialogClose className="border-input rounded border px-4 py-1.5 text-[13px]">
              {t("common.cancel")}
            </DialogClose>
            <button
              className="bg-primary text-primary-foreground rounded px-4 py-1.5 text-[13px] font-medium"
              onClick={handleApply}
              type="button"
            >
              {t("common.apply")}
            </button>
          </div>
        </DialogPopup>
      </DialogPortal>
    </Dialog>
  );
}

// packages/vue/src/components/dialogs/ImagePositionDialog.vue
<!--
  Image Position dialog — ported from the upstream docx-editor Vue adapter.

  TODO(i18n): all `dialogs.imagePosition.*` and `common.*` keys are kept verbatim;
  the folio catalog has no equivalents yet. The two "Mode" labels and the
  "Distance from text (px)" legend were hard-coded English in upstream and remain so.
-->
<template>
  <div v-if="isOpen" class="ipd-overlay" @mousedown.self="$emit('close')">
    <div class="ipd-dialog" @keydown.escape="$emit('close')">
      <div class="ipd-dialog__header">{{ t('dialogs.imagePosition.title') }}</div>

      <div class="ipd-dialog__body">
        <!-- Horizontal -->
        <fieldset class="ipd-fieldset">
          <legend class="ipd-legend">{{ t('dialogs.imagePosition.horizontal') }}</legend>
          <div class="ipd-row">
            <label class="ipd-label">Mode</label>
            <select v-model="hMode" class="ipd-select">
              <option value="align">{{ t('dialogs.imagePosition.alignment') }}</option>
              <option value="offset">{{ t('dialogs.imagePosition.offset') }}</option>
            </select>
          </div>
          <div v-if="hMode === 'align'" class="ipd-row">
            <label class="ipd-label">{{ t('dialogs.imagePosition.align') }}</label>
            <select v-model="hAlign" class="ipd-select">
              <option value="left">{{ t('dialogs.imagePosition.alignOptions.left') }}</option>
              <option value="center">{{ t('dialogs.imagePosition.alignOptions.center') }}</option>
              <option value="right">{{ t('dialogs.imagePosition.alignOptions.right') }}</option>
            </select>
          </div>
          <div v-else class="ipd-row">
            <label class="ipd-label">{{ t('dialogs.imagePosition.offsetPx') }}</label>
            <input v-model.number="hOffset" type="number" class="ipd-input" />
          </div>
          <div class="ipd-row">
            <label class="ipd-label">{{ t('dialogs.imagePosition.relativeTo') }}</label>
            <select v-model="hRelativeTo" class="ipd-select">
              <option value="page">{{ t('dialogs.imagePosition.relativeOptions.page') }}</option>
              <option value="column">{{ t('dialogs.imagePosition.relativeOptions.column') }}</option>
              <option value="margin">{{ t('dialogs.imagePosition.relativeOptions.margin') }}</option>
              <option value="character">{{ t('dialogs.imagePosition.relativeOptions.character') }}</option>
            </select>
          </div>
        </fieldset>

        <!-- Vertical -->
        <fieldset class="ipd-fieldset">
          <legend class="ipd-legend">{{ t('dialogs.imagePosition.vertical') }}</legend>
          <div class="ipd-row">
            <label class="ipd-label">Mode</label>
            <select v-model="vMode" class="ipd-select">
              <option value="align">{{ t('dialogs.imagePosition.alignment') }}</option>
              <option value="offset">{{ t('dialogs.imagePosition.offset') }}</option>
            </select>
          </div>
          <div v-if="vMode === 'align'" class="ipd-row">
            <label class="ipd-label">{{ t('dialogs.imagePosition.align') }}</label>
            <select v-model="vAlign" class="ipd-select">
              <option value="top">{{ t('dialogs.imagePosition.alignOptions.top') }}</option>
              <option value="center">{{ t('dialogs.imagePosition.alignOptions.center') }}</option>
              <option value="bottom">{{ t('dialogs.imagePosition.alignOptions.bottom') }}</option>
            </select>
          </div>
          <div v-else class="ipd-row">
            <label class="ipd-label">{{ t('dialogs.imagePosition.offsetPx') }}</label>
            <input v-model.number="vOffset" type="number" class="ipd-input" />
          </div>
          <div class="ipd-row">
            <label class="ipd-label">{{ t('dialogs.imagePosition.relativeTo') }}</label>
            <select v-model="vRelativeTo" class="ipd-select">
              <option value="page">{{ t('dialogs.imagePosition.relativeOptions.page') }}</option>
              <option value="margin">{{ t('dialogs.imagePosition.relativeOptions.margin') }}</option>
              <option value="paragraph">{{ t('dialogs.imagePosition.relativeOptions.paragraph') }}</option>
              <option value="line">{{ t('dialogs.imagePosition.relativeOptions.line') }}</option>
            </select>
          </div>
        </fieldset>

        <!-- Distance from text -->
        <fieldset class="ipd-fieldset">
          <legend class="ipd-legend">Distance from text (px)</legend>
          <div class="ipd-row">
            <label class="ipd-label">{{ t('dialogs.imagePosition.alignOptions.top') }}</label>
            <input v-model.number="distTop" type="number" class="ipd-input" min="0" />
            <label class="ipd-label" style="width:60px">{{ t('dialogs.imagePosition.alignOptions.bottom') }}</label>
            <input v-model.number="distBottom" type="number" class="ipd-input" min="0" />
          </div>
          <div class="ipd-row">
            <label class="ipd-label">{{ t('dialogs.imagePosition.alignOptions.left') }}</label>
            <input v-model.number="distLeft" type="number" class="ipd-input" min="0" />
            <label class="ipd-label" style="width:60px">{{ t('dialogs.imagePosition.alignOptions.right') }}</label>
            <input v-model.number="distRight" type="number" class="ipd-input" min="0" />
          </div>
        </fieldset>
      </div>

      <div class="ipd-dialog__footer">
        <button class="ipd-btn" @click="$emit('close')">{{ t('common.cancel') }}</button>
        <button class="ipd-btn ipd-btn--primary" @click="apply">{{ t('common.apply') }}</button>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, watch } from 'vue';
import { useTranslation } from '../../i18n';

const { t } = useTranslation();

export type ImagePositionData = {
  horizontal?: { relativeTo?: string; posOffset?: number; align?: string };
  vertical?: { relativeTo?: string; posOffset?: number; align?: string };
  distTop?: number;
  distBottom?: number;
  distLeft?: number;
  distRight?: number;
}

const props = defineProps<{
  isOpen: boolean;
  currentData?: ImagePositionData;
}>();

const emit = defineEmits<{
  (e: 'close'): void;
  (e: 'apply', data: ImagePositionData): void;
}>();

const hMode = ref<'align' | 'offset'>('align');
const hAlign = ref('left');
const hOffset = ref(0);
const hRelativeTo = ref('column');
const vMode = ref<'align' | 'offset'>('align');
const vAlign = ref('top');
const vOffset = ref(0);
const vRelativeTo = ref('paragraph');
const distTop = ref(0);
const distBottom = ref(0);
const distLeft = ref(0);
const distRight = ref(0);

watch(
  () => props.isOpen,
  (open) => {
    if (!open) return;
    const d = props.currentData;
    if (d?.horizontal?.align) {
      hMode.value = 'align';
      hAlign.value = d.horizontal.align;
    } else if (d?.horizontal?.posOffset != null) {
      hMode.value = 'offset';
      hOffset.value = d.horizontal.posOffset;
    }
    hRelativeTo.value = d?.horizontal?.relativeTo ?? 'column';
    if (d?.vertical?.align) {
      vMode.value = 'align';
      vAlign.value = d.vertical.align;
    } else if (d?.vertical?.posOffset != null) {
      vMode.value = 'offset';
      vOffset.value = d.vertical.posOffset;
    }
    vRelativeTo.value = d?.vertical?.relativeTo ?? 'paragraph';
    distTop.value = d?.distTop ?? 0;
    distBottom.value = d?.distBottom ?? 0;
    distLeft.value = d?.distLeft ?? 0;
    distRight.value = d?.distRight ?? 0;
  }
);

function apply() {
  const data: ImagePositionData = {
    horizontal: {
      relativeTo: hRelativeTo.value,
      ...(hMode.value === 'align' ? { align: hAlign.value } : { posOffset: hOffset.value }),
    },
    vertical: {
      relativeTo: vRelativeTo.value,
      ...(vMode.value === 'align' ? { align: vAlign.value } : { posOffset: vOffset.value }),
    },
    distTop: distTop.value,
    distBottom: distBottom.value,
    distLeft: distLeft.value,
    distRight: distRight.value,
  };
  emit('apply', data);
  emit('close');
}
</script>

<style scoped>
.ipd-overlay { position: fixed; inset: 0; background: var(--doc-overlay); display: flex; align-items: center; justify-content: center; z-index: 10000; }
.ipd-dialog { background: var(--doc-surface); border-radius: 8px; box-shadow: 0 4px 20px var(--doc-shadow); width: 420px; max-width: 90vw; }
.ipd-dialog__header { padding: 16px 20px 12px; border-bottom: 1px solid var(--doc-border); font-size: 16px; font-weight: 600; color: var(--doc-text); }
.ipd-dialog__body { padding: 12px 20px; display: flex; flex-direction: column; gap: 12px; max-height: 60vh; overflow-y: auto; }
.ipd-dialog__footer { padding: 12px 20px 16px; border-top: 1px solid var(--doc-border); display: flex; justify-content: flex-end; gap: 8px; }
.ipd-fieldset { border: 1px solid var(--doc-border); border-radius: 6px; padding: 10px 12px; margin: 0; }
.ipd-legend { font-size: 12px; font-weight: 600; color: var(--doc-text-muted); padding: 0 4px; }
.ipd-row { display: flex; align-items: center; gap: 8px; margin-bottom: 6px; }
.ipd-row:last-child { margin-bottom: 0; }
.ipd-label { width: 70px; font-size: 13px; color: var(--doc-text-muted); flex-shrink: 0; }
.ipd-input, .ipd-select { flex: 1; padding: 5px 8px; border: 1px solid var(--doc-border-dark); border-radius: 4px; font-size: 13px; }
.ipd-btn { padding: 6px 16px; font-size: 13px; border: 1px solid var(--doc-border-dark); border-radius: 4px; cursor: pointer; background: var(--doc-surface); }
.ipd-btn--primary { background: var(--doc-primary); color: var(--doc-on-primary); border-color: var(--doc-primary); }
</style>
