// packages/react/src/components/dialogs/PasteSpecialDialog.tsx
import { useEffect, useId, useState } from "react";

import { useFolioUI } from "../../ui/folio-ui";
import {
  DIALOG_BACKDROP_CLASS,
  DIALOG_BODY_CLASS,
  DIALOG_FOOTER_CLASS,
  DIALOG_LABEL_CLASS,
  DIALOG_POPUP_CLASS,
  DIALOG_PRIMARY_BUTTON_CLASS,
  DIALOG_SECONDARY_BUTTON_CLASS,
  DIALOG_TITLE_CLASS,
} from "./dialogChrome";

export type PasteSpecialMode = "keepFormatting" | "mergeFormatting" | "plainText";

export type PasteSpecialDialogProps = {
  isOpen: boolean;
  onClose: () => void;
  onPaste: (mode: PasteSpecialMode) => void;
  defaultMode?: PasteSpecialMode;
};

const PASTE_MODES: Array<{ value: PasteSpecialMode; label: string; description: string }> = [
  {
    value: "keepFormatting",
    label: "Keep source formatting",
    description: "Preserve styles, links, and inline formatting from the clipboard.",
  },
  {
    value: "mergeFormatting",
    label: "Merge formatting",
    description: "Keep useful inline formatting while matching the destination paragraph.",
  },
  {
    value: "plainText",
    label: "Unformatted text",
    description: "Paste text only and use the destination formatting.",
  },
];

export function PasteSpecialDialog({
  isOpen,
  onClose,
  onPaste,
  defaultMode = "plainText",
}: PasteSpecialDialogProps) {
  const {
    Root: Dialog,
    Portal: DialogPortal,
    Backdrop: DialogBackdrop,
    Popup: DialogPopup,
    Title: DialogTitle,
    Close: DialogClose,
  } = useFolioUI().Dialog;
  const id = useId();
  const [mode, setMode] = useState<PasteSpecialMode>(defaultMode);

  useEffect(() => {
    if (isOpen) {
      setMode(defaultMode);
    }
  }, [isOpen, defaultMode]);

  const handlePaste = () => {
    onPaste(mode);
    onClose();
  };

  return (
    <Dialog
      open={isOpen}
      onOpenChange={(open) => {
        if (!open) {
          onClose();
        }
      }}
    >
      <DialogPortal>
        <DialogBackdrop className={DIALOG_BACKDROP_CLASS} />
        <DialogPopup className={DIALOG_POPUP_CLASS}>
          <DialogTitle className={DIALOG_TITLE_CLASS}>Paste Special</DialogTitle>

          <div className={DIALOG_BODY_CLASS}>
            <fieldset className="flex flex-col gap-3">
              <legend className={DIALOG_LABEL_CLASS}>Paste mode</legend>
              {PASTE_MODES.map((option) => {
                const optionId = `${id}-paste-special-${option.value}`;
                return (
                  <label className="flex items-start gap-3" htmlFor={optionId} key={option.value}>
                    <input
                      checked={mode === option.value}
                      id={optionId}
                      onChange={() => setMode(option.value)}
                      type="radio"
                    />
                    <span className="flex flex-col gap-1">
                      <span className="text-foreground text-[13px] font-medium">
                        {option.label}
                      </span>
                      <span className="text-muted-foreground text-xs">{option.description}</span>
                    </span>
                  </label>
                );
              })}
            </fieldset>
          </div>

          <div className={DIALOG_FOOTER_CLASS}>
            <DialogClose className={DIALOG_SECONDARY_BUTTON_CLASS}>Cancel</DialogClose>
            <button className={DIALOG_PRIMARY_BUTTON_CLASS} onClick={handlePaste} type="button">
              Paste
            </button>
          </div>
        </DialogPopup>
      </DialogPortal>
    </Dialog>
  );
}

// packages/vue/src/components/dialogs/PasteSpecialDialog.vue
<template>
  <FolioDialog
    :open="isOpen"
    aria-label="Paste Special"
    :style="{ minWidth: '360px', maxWidth: '520px', width: '100%' }"
    @close="$emit('close')"
  >
    <div class="dialog__header">Paste Special</div>
    <div class="dialog__body">
      <fieldset class="options">
        <legend class="options__legend">Paste mode</legend>
        <label v-for="option in PASTE_MODES" :key="option.value" class="option">
          <input v-model="mode" type="radio" :value="option.value" />
          <span class="option__body">
            <span class="option__label">{{ option.label }}</span>
            <span class="option__description">{{ option.description }}</span>
          </span>
        </label>
      </fieldset>
    </div>
    <div class="dialog__footer">
      <button class="dialog__btn" @click="$emit('close')">Cancel</button>
      <button class="dialog__btn dialog__btn--primary" @click="paste">Paste</button>
    </div>
  </FolioDialog>
</template>

<script setup lang="ts">
import { ref, watch } from "vue";
import { useFolioUI } from "../../ui/folio-ui";

const { Dialog: FolioDialog } = useFolioUI();

export type PasteSpecialMode = "keepFormatting" | "mergeFormatting" | "plainText";

const PASTE_MODES: Array<{ value: PasteSpecialMode; label: string; description: string }> = [
  {
    value: "keepFormatting",
    label: "Keep source formatting",
    description: "Preserve styles, links, and inline formatting from the clipboard.",
  },
  {
    value: "mergeFormatting",
    label: "Merge formatting",
    description: "Keep useful inline formatting while matching the destination paragraph.",
  },
  {
    value: "plainText",
    label: "Unformatted text",
    description: "Paste text only and use the destination formatting.",
  },
];

const props = withDefaults(
  defineProps<{
    isOpen: boolean;
    defaultMode?: PasteSpecialMode;
  }>(),
  { defaultMode: "plainText" },
);

const emit = defineEmits<{
  (e: "close"): void;
  (e: "paste", mode: PasteSpecialMode): void;
}>();

const mode = ref<PasteSpecialMode>(props.defaultMode);

watch(
  () => props.isOpen,
  (open) => {
    if (open) mode.value = props.defaultMode;
  },
);

function paste() {
  emit("paste", mode.value);
  emit("close");
}
</script>

<style scoped>
.dialog__header {
  padding: 16px 20px 12px;
  border-bottom: 1px solid var(--doc-border);
  font-size: 16px;
  font-weight: 600;
  color: var(--doc-text);
}
.dialog__body {
  padding: 16px 20px;
  display: flex;
  flex-direction: column;
  gap: 16px;
}
.dialog__footer {
  padding: 12px 20px 16px;
  border-top: 1px solid var(--doc-border);
  display: flex;
  justify-content: flex-end;
  gap: 8px;
}
.options {
  display: flex;
  flex-direction: column;
  gap: 12px;
  padding: 0;
  margin: 0;
  border: 0;
}
.options__legend {
  margin-bottom: 4px;
  font-size: 13px;
  color: var(--doc-text-muted);
}
.option {
  display: flex;
  align-items: flex-start;
  gap: 12px;
  color: var(--doc-text);
}
.option__body {
  display: flex;
  flex-direction: column;
  gap: 4px;
}
.option__label {
  font-size: 13px;
  font-weight: 600;
}
.option__description {
  font-size: 12px;
  color: var(--doc-text-muted);
}
.dialog__btn {
  border: 1px solid var(--doc-border);
  border-radius: 4px;
  background: var(--doc-surface);
  color: var(--doc-text);
  padding: 6px 16px;
  font-size: 13px;
  cursor: pointer;
}
.dialog__btn--primary {
  border-color: var(--doc-primary);
  background: var(--doc-primary);
  color: white;
  font-weight: 600;
}
</style>
