// packages/vue/src/components/AnonymizationRectsOverlay.vue
<!--
  Anonymization Rects Overlay (Vue)

  Paints anonymization-term highlights on top of the rendered paged document.
  Decoration spans live in the hidden ProseMirror editor and never reach the
  visible page DOM, so we project the same ranges onto container-relative
  rectangles (via core's `projectRangesToRects`) and stack a coloured span per
  line on this absolutely-positioned overlay.

  Port of the React `AnonymizationRectsOverlay`. The projection returns unscaled
  (page-space) rects — the Vue pages carry `transform: scale(zoom)` but this
  overlay does not, so every coordinate is multiplied back by `zoom` at render
  time (the same convention as CommentMarginMarkers.vue).

  Pointer events stay disabled on every node so text selection, caret placement,
  and the editor's own handlers keep working through the overlay. The click
  hit-test instead listens on `document` and bounding-rect-tests the click
  position against the overlay spans, so the editor still receives the click and
  this fires alongside it.
-->
<template>
  <div ref="rootRef" class="folio-anonymization-overlay" data-folio-anonymization-overlay="">
    <template v-for="group in groups" :key="`${group.label}:${group.canonical}`">
      <span
        v-for="(rect, idx) in group.rects"
        :key="`${group.canonical}:${idx}:${rect.left}:${rect.top}`"
        :class="[
          'folio-anonymization-term',
          `folio-anonymization-term--${slugAnonymizationLabel(group.label)}`,
        ]"
        :data-folio-anonymization-label="group.label"
        :data-folio-anonymization-canonical="group.canonical"
        :data-folio-anonymization-selected="
          group.canonical === selectedCanonical ? 'true' : undefined
        "
        :title="`Anonymized: ${group.canonical}`"
        :style="{
          position: 'absolute',
          left: `${rect.left}px`,
          top: `${rect.top}px`,
          width: `${rect.width}px`,
          height: `${rect.height}px`,
        }"
      />
    </template>
  </div>
</template>

<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref, watch } from "vue";
import type { EditorState } from "prosemirror-state";
import type { EditorView } from "prosemirror-view";

import { createLatestRequestGate } from "@stll/folio-core/controller/latestRequestGate";
import type { FlowBlock, Layout, Measure } from "@stll/folio-core/layout-engine/types";
import { projectRangesToRects } from "@stll/folio-core/paged-layout/rangeProjection";
import { scrollEditorElementIntoView } from "@stll/folio-core/paged-layout/editorScrollRoot";
import type { AnonymizationMatch } from "@stll/folio-core/prosemirror/plugins/anonymizationDecorations";
import {
  getAnonymizationMatches,
  slugAnonymizationLabel,
} from "@stll/folio-core/prosemirror/plugins/anonymizationDecorations";

/** One canonical's projected rectangles in overlay (post-zoom) pixel space. */
type AnonymizationRectGroup = {
  rects: { left: number; top: number; width: number; height: number }[];
  label: string;
  canonical: string;
};

const props = defineProps<{
  getView: () => EditorView | null;
  getPagesContainer: () => HTMLElement | null;
  /** Reactive editor state — changes on every transaction, including the
   *  meta-only term push that a doc edit does not cover. */
  editorState: EditorState | null;
  zoom: number;
  layout: Layout | null;
  blocks: FlowBlock[];
  measures: Measure[];
  onTermClick?: ((canonical: string, label: string) => void) | undefined;
  selectedCanonical?: string | null | undefined;
  selectionSeq?: number | undefined;
}>();

const rootRef = ref<HTMLDivElement | null>(null);
const groups = ref<AnonymizationRectGroup[]>([]);

const requestGate = createLatestRequestGate();
let rafId: number | null = null;

function scheduleProject(): void {
  if (rafId !== null) {
    cancelAnimationFrame(rafId);
  }
  rafId = requestAnimationFrame(() => {
    rafId = null;
    void project();
  });
}

async function project(): Promise<void> {
  const isCurrentRequest = requestGate.begin();
  const view = props.getView();
  const pagesContainer = props.getPagesContainer();
  const state = props.editorState;
  if (!view || !pagesContainer || !state) {
    groups.value = [];
    return;
  }
  const matches = getAnonymizationMatches(state);
  if (matches.length === 0) {
    groups.value = [];
    return;
  }
  const projected = await projectRangesToRects<AnonymizationMatch>(matches, {
    pagesContainer,
    zoom: props.zoom,
    layout: props.layout,
    blocks: props.blocks,
    measures: props.measures,
  });
  if (!isCurrentRequest()) {
    return;
  }
  const z = props.zoom;
  groups.value = projected.map(({ range, rects }) => ({
    label: range.label,
    canonical: range.canonical,
    rects: rects.map((rect) => ({
      left: rect.x * z,
      top: rect.y * z,
      width: rect.width * z,
      height: rect.height * z,
    })),
  }));
}

watch(
  () => [props.editorState, props.zoom, props.layout, props.blocks, props.measures],
  () => scheduleProject(),
);

// ---- Selection scroll-into-view -----------------------------------------
// Repeated sidebar selections of the same canonical step through every hit,
// wrapping at the end; a new canonical resets to the first occurrence.
let cycle: { canonical: string; index: number } | null = null;

function scrollSelectedIntoView(): void {
  const root = rootRef.value;
  const canonical = props.selectedCanonical;
  if (!root || !canonical) {
    cycle = null;
    return;
  }
  const spans = root.querySelectorAll<HTMLElement>(
    `[data-folio-anonymization-canonical="${CSS.escape(canonical)}"]`,
  );
  if (spans.length === 0) {
    return;
  }
  const nextIndex = cycle?.canonical === canonical ? (cycle.index + 1) % spans.length : 0;
  cycle = { canonical, index: nextIndex };
  scrollEditorElementIntoView(spans.item(nextIndex));
}

watch(
  () => [props.selectedCanonical, props.selectionSeq],
  () => scrollSelectedIntoView(),
  // Query the DOM after the overlay has (re)rendered, matching the React
  // adapter's post-commit `useEffect` timing.
  { flush: "post" },
);

// ---- Document-level click hit-test --------------------------------------
function handleDocumentClick(event: MouseEvent): void {
  if (event.button !== 0 || !props.onTermClick) {
    return;
  }
  const root = rootRef.value;
  if (!root) {
    return;
  }
  const spans = root.querySelectorAll<HTMLElement>("[data-folio-anonymization-canonical]");
  // Reverse paint order so the topmost rect wins when several overlap.
  for (let i = spans.length - 1; i >= 0; i -= 1) {
    const el = spans.item(i);
    if (!el) {
      continue;
    }
    const rect = el.getBoundingClientRect();
    const inside =
      event.clientX >= rect.left &&
      event.clientX < rect.right &&
      event.clientY >= rect.top &&
      event.clientY < rect.bottom;
    if (inside) {
      const canonical = el.dataset["folioAnonymizationCanonical"];
      const label = el.dataset["folioAnonymizationLabel"];
      if (canonical && label) {
        props.onTermClick(canonical, label);
      }
      return;
    }
  }
}

onMounted(() => {
  document.addEventListener("click", handleDocumentClick);
  scheduleProject();
});

onBeforeUnmount(() => {
  requestGate.invalidate();
  document.removeEventListener("click", handleDocumentClick);
  if (rafId !== null) {
    cancelAnimationFrame(rafId);
    rafId = null;
  }
});
</script>

<style scoped>
.folio-anonymization-overlay {
  position: absolute;
  inset: 0;
  pointer-events: none;
}

/* Single thin blue underline under every span the redaction pipeline would
   redact. No fill so the doc stays readable. Mirrors React editor.css. */
.folio-anonymization-term {
  background-color: transparent;
  box-shadow: inset 0 -2px 0 0 rgb(37 99 235 / 0.8);
  border-radius: 2px;
  transition:
    background-color 150ms ease,
    box-shadow 150ms ease;
}

.folio-anonymization-term:hover {
  background-color: rgb(37 99 235 / 0.12);
}

.folio-anonymization-term[data-folio-anonymization-selected="true"] {
  background-color: rgb(37 99 235 / 0.2);
  box-shadow:
    inset 0 -2px 0 0 rgb(37 99 235 / 0.9),
    0 0 0 2px rgb(37 99 235 / 0.35);
}
</style>

// packages/react/src/paged-editor/AnonymizationRectsOverlay.tsx
/**
 * Anonymization Rects Overlay
 *
 * Paints anonymization-term highlights on top of the rendered
 * paged document. Decoration spans live in the hidden
 * ProseMirror editor and never reach the visible page DOM, so
 * we project the same ranges onto container-relative rectangles
 * (via {@link selectionToRects}) and stack a coloured div per
 * line on this absolutely-positioned overlay.
 *
 * Pointer events stay disabled on every node so text selection,
 * caret placement, drag-selects, and the editor's own
 * mousedown/click handlers continue to work through the
 * overlay. The sidebar bridge instead listens on `document`
 * for clicks and hit-tests the click coordinates against the
 * overlay spans via `elementsFromPoint`. That way the editor
 * still receives the click and the bridge fires alongside it,
 * with no contention over `mousedown`.
 *
 * When `selectedCanonical` is set, every rect for that
 * canonical gets `data-folio-anonymization-selected="true"`
 * and the first matching rect is scrolled into view (only on
 * `selectionSeq` changes — repeated clicks of the same
 * canonical in the sidebar re-trigger the scroll).
 */

import React, { useEffect, useRef } from "react";

import type { SelectionRect } from "@stll/folio-core/layout-bridge/engine/selectionRects";
import { scrollEditorElementIntoView } from "@stll/folio-core/paged-layout/editorScrollRoot";
import { slugAnonymizationLabel } from "@stll/folio-core/prosemirror/plugins/anonymizationDecorations";

export type AnonymizationRectGroup = {
  /** Same shape as SelectionOverlay — adjusted into container space. */
  rects: SelectionRect[];
  /** Per-occurrence label slug (e.g. "person", "organization"). */
  label: string;
  /** Canonical surface form, surfaced through the title tooltip. */
  canonical: string;
};

export type AnonymizationRectsOverlayProps = {
  groups: AnonymizationRectGroup[];
  /**
   * Called when the user clicks a highlight. Receives the
   * canonical surface form and label slug so the host can
   * forward to a sidebar-bridge store. The overlay uses a
   * `document`-level click + hit-test to detect this, leaving
   * the editor's own mousedown/click handlers untouched.
   */
  onTermClick?: ((canonical: string, label: string) => void) | undefined;
  /**
   * Canonical to mark as selected. Matching spans get a
   * data-attribute so CSS can highlight them; the first
   * matching rect scrolls into view on every `selectionSeq`
   * change.
   */
  selectedCanonical?: string | null | undefined;
  /**
   * Monotonically-increasing token from the bridge store.
   * Bumping it re-triggers the scroll even when the canonical
   * itself didn't change.
   */
  selectionSeq?: number | undefined;
};

const overlayStyles: React.CSSProperties = {
  position: "absolute",
  top: 0,
  left: "50%",
  width: "100vw",
  height: "100%",
  transform: "translateX(-50%)",
  pointerEvents: "none",
  zIndex: 0,
};

export const AnonymizationRectsOverlay = ({
  groups,
  onTermClick,
  selectedCanonical = null,
  selectionSeq,
}: AnonymizationRectsOverlayProps) => {
  // All spans grouped by canonical. Repeated sidebar selections
  // of the same canonical advance through `spansByCanonical`,
  // wrapping at the end, so the user isn't stuck on the first
  // occurrence and can step through every hit.
  const spansByCanonical = useRef(new Map<string, HTMLSpanElement[]>());
  spansByCanonical.current = new Map();

  // Last canonical scrolled to + index inside its span list.
  // Used to advance on repeat selections of the same canonical
  // and reset to 0 when the canonical changes.
  const cycleRef = useRef<{ canonical: string; index: number } | null>(null);

  useEffect(() => {
    if (!selectedCanonical) {
      cycleRef.current = null;
      return;
    }
    const spans = spansByCanonical.current.get(selectedCanonical) ?? [];
    if (spans.length === 0) {
      return;
    }
    let nextIndex: number;
    if (cycleRef.current?.canonical === selectedCanonical) {
      nextIndex = (cycleRef.current.index + 1) % spans.length;
    } else {
      nextIndex = 0;
    }
    cycleRef.current = { canonical: selectedCanonical, index: nextIndex };
    const el = spans[nextIndex];
    if (el) {
      scrollEditorElementIntoView(el);
    }
  }, [selectedCanonical, selectionSeq]);

  // Track the overlay's root so we only hit-test our own
  // spans and ignore clicks elsewhere in the page.
  const overlayRef = useRef<HTMLDivElement>(null);

  // Document-level hit-test. The overlay spans keep
  // `pointer-events: none`, so the editor receives clicks
  // normally (caret placement, drag-selects, the existing
  // mousedown handler on `.paged-editor__pages`). After the
  // click bubbles, we iterate the overlay spans and
  // bounding-rect-test against the click position.
  // (`elementsFromPoint` skips `pointer-events: none`
  // elements, so it can't be used here.)
  useEffect(() => {
    if (!onTermClick) {
      return;
    }
    const handleClick = (event: MouseEvent) => {
      // Ignore non-primary clicks; right-click should reach the
      // editor's context menu unchanged.
      if (event.button !== 0) {
        return;
      }
      const root = overlayRef.current;
      if (!root) {
        return;
      }
      const spans = root.querySelectorAll<HTMLElement>("[data-folio-anonymization-canonical]");
      // Iterate in reverse paint order so the topmost rect wins
      // when several overlap at the same point.
      for (let i = spans.length - 1; i >= 0; i--) {
        const el = spans[i];
        if (!el) {
          continue;
        }
        const rect = el.getBoundingClientRect();
        if (
          event.clientX >= rect.left &&
          event.clientX < rect.right &&
          event.clientY >= rect.top &&
          event.clientY < rect.bottom
        ) {
          const canonical = el.dataset["folioAnonymizationCanonical"];
          const label = el.dataset["folioAnonymizationLabel"];
          if (canonical && label) {
            onTermClick(canonical, label);
          }
          return;
        }
      }
    };
    document.addEventListener("click", handleClick);
    return () => document.removeEventListener("click", handleClick);
  }, [onTermClick]);

  if (groups.length === 0) {
    return null;
  }

  return (
    <div ref={overlayRef} style={overlayStyles} data-folio-anonymization-overlay="">
      {groups.flatMap((group) => {
        const isSelected = selectedCanonical === group.canonical;
        return group.rects.map((rect, idx) => (
          <span
            key={`${group.label}:${group.canonical}:${idx}:${rect.pageIndex}:${rect.x}:${rect.y}`}
            ref={(node) => {
              if (node) {
                const list = spansByCanonical.current.get(group.canonical) ?? [];
                list.push(node);
                spansByCanonical.current.set(group.canonical, list);
              }
            }}
            className={`folio-anonymization-term folio-anonymization-term--${slugAnonymizationLabel(group.label)}`}
            data-folio-anonymization-label={group.label}
            data-folio-anonymization-canonical={group.canonical}
            data-folio-anonymization-selected={isSelected ? "true" : undefined}
            title={`Anonymized: ${group.canonical}`}
            style={{
              position: "absolute",
              left: rect.x,
              top: rect.y,
              width: rect.width,
              height: rect.height,
            }}
          />
        ));
      })}
    </div>
  );
};
