// packages/vue/src/components/ContentControlWidgetsOverlay.vue
<!-- Thin Vue renderer for the shared content-control widget controller. -->
<template>
  <Teleport to="body">
    <div
      v-if="snapshot.status !== 'closed'"
      :class="['content-control-picker', portalClass]"
      :style="pickerStyle"
      role="dialog"
      :aria-label="
        snapshot.status === 'dropdown'
          ? t('contentControlDropdownAriaLabel')
          : t('contentControlDateAriaLabel')
      "
      @mousedown.stop
    >
      <div v-if="snapshot.status === 'dropdown'" class="content-control-picker__items" role="menu">
        <div v-if="snapshot.items.length === 0" class="content-control-picker__empty">
          {{ t("contentControlDropdownNoOptions") }}
        </div>
        <template v-else>
          <FolioButton
            v-for="item in snapshot.items"
            :key="`${item.value}::${item.displayText}`"
            class-name="content-control-picker__item"
            type="button"
            role="menuitem"
            variant="ghost"
            size="sm"
            @mousedown.prevent
            @click="controller.pickDropdown(item.value)"
          >
            {{ item.displayText }}
          </FolioButton>
        </template>
      </div>
      <DatePickerPopover
        v-else-if="snapshot.status === 'date'"
        :value="snapshot.currentValue"
        :default-open="true"
        @change="onDateChange"
      />
    </div>
  </Teleport>
</template>

<script setup lang="ts">
import { computed, onBeforeUnmount, shallowRef, watch, type CSSProperties } from "vue";
import type { EditorView } from "prosemirror-view";

import { ContentControlWidgetController } from "@stll/folio-core/controller/contentControlWidgetController";
import { useDocxPortalClass } from "../composables/usePortalClass";
import { useTranslation } from "../i18n";
import { useFolioUI } from "../ui/folio-ui";

const props = defineProps<{ view: EditorView | null }>();

const { t } = useTranslation();
const { Button: FolioButton, DatePickerPopover } = useFolioUI();
const portalClass = useDocxPortalClass();
const controller = new ContentControlWidgetController();
const snapshot = shallowRef(controller.getSnapshot());
const unsubscribe = controller.subscribe(() => {
  snapshot.value = controller.getSnapshot();
});

watch(
  () => props.view,
  (view) => controller.bind(view),
  { immediate: true },
);

onBeforeUnmount(() => {
  unsubscribe();
  controller.destroy();
});

const pickerStyle = computed<CSSProperties>(() => {
  if (snapshot.value.status === "closed") {
    return {};
  }
  return {
    insetInlineStart: `${snapshot.value.position.x}px`,
    top: `${snapshot.value.position.y}px`,
  };
});

const onDateChange = (value: string | null): void => {
  if (value) {
    controller.pickDate(value);
  }
};
</script>

<style scoped>
.content-control-picker {
  position: fixed;
  z-index: 9999;
  min-width: 10rem;
  padding: 4px;
  color: var(--doc-text);
  background: var(--doc-surface);
  border: 1px solid var(--doc-border);
  border-radius: 6px;
  box-shadow: var(--doc-shadow-md, 0 4px 12px rgb(0 0 0 / 15%));
}

.content-control-picker__items {
  display: flex;
  flex-direction: column;
}

.content-control-picker__item {
  width: 100%;
  padding: 6px 8px;
  color: inherit;
  font: inherit;
  text-align: start;
  cursor: pointer;
  background: transparent;
  border: 0;
  border-radius: 4px;
}

.content-control-picker__item:hover,
.content-control-picker__item:focus-visible {
  background: var(--doc-bg-hover);
  outline: none;
}

.content-control-picker__empty {
  padding: 6px 8px;
  color: var(--doc-text-muted);
  font-size: 13px;
}
</style>

// packages/react/src/components/ContentControlWidgetsOverlay.tsx
/** Thin React renderer for the shared content-control widget controller. */

import { useCallback, useEffect, useMemo, useSyncExternalStore } from "react";
import { createPortal } from "react-dom";

import type { EditorView } from "prosemirror-view";
import { useTranslations } from "use-intl";

import { ContentControlWidgetController } from "@stll/folio-core/controller/contentControlWidgetController";
import type { ContentControlListItem } from "@stll/folio-core/controller/contentControlWidgetController";
import { useFolioUI } from "../ui/folio-ui";

type FolioMenuItem = ReturnType<typeof useFolioUI>["Menu"]["Item"];

type ContentControlWidgetsOverlayProps = {
  getEditorView: () => EditorView | null;
};

export function ContentControlWidgetsOverlay({ getEditorView }: ContentControlWidgetsOverlayProps) {
  const folioUI = useFolioUI();
  const { Item: MenuItem } = folioUI.Menu;
  const DatePickerPopover = folioUI.DatePickerPopover;
  const t = useTranslations("folio");
  const controller = useMemo(() => new ContentControlWidgetController(), []);
  const snapshot = useSyncExternalStore(
    controller.subscribe,
    controller.getSnapshot,
    controller.getSnapshot,
  );
  const view = getEditorView();

  useEffect(() => {
    controller.bind(view);
    return () => controller.destroy();
  }, [controller, view]);

  const onDropdownPick = useCallback(
    (value: string) => controller.pickDropdown(value),
    [controller],
  );
  const onDateChange = useCallback(
    (value: string | null) => (value ? controller.pickDate(value) : false),
    [controller],
  );

  if (snapshot.status === "closed") {
    return null;
  }

  const style = {
    position: "fixed" as const,
    top: `${snapshot.position.y}px`,
    insetInlineStart: `${snapshot.position.x}px`,
    zIndex: 9999,
  };

  return createPortal(
    <div className="folio-root" style={{ display: "contents" }}>
      <div
        role="dialog"
        aria-label={
          snapshot.status === "dropdown"
            ? t("contentControlDropdownAriaLabel")
            : t("contentControlDateAriaLabel")
        }
        style={style}
        className="bg-popover text-popover-foreground min-w-[10rem] rounded-md border p-1 shadow-md"
      >
        {snapshot.status === "dropdown" && (
          <div role="menu" className="flex flex-col">
            {snapshot.items.length === 0 ? (
              <div className="text-muted-foreground px-2 py-1 text-sm">
                {t("contentControlDropdownNoOptions")}
              </div>
            ) : (
              snapshot.items.map((item) => (
                <ContentControlDropdownItem
                  key={`${item.value}::${item.displayText}`}
                  item={item}
                  MenuItem={MenuItem}
                  onPick={onDropdownPick}
                />
              ))
            )}
          </div>
        )}
        {snapshot.status === "date" && (
          <DatePickerPopover
            clearLabel={t("clearDate")}
            defaultOpen
            onChange={onDateChange}
            showIcon={false}
            value={snapshot.currentValue}
          />
        )}
      </div>
    </div>,
    document.body,
  );
}

type ContentControlDropdownItemProps = {
  item: ContentControlListItem;
  MenuItem: FolioMenuItem;
  onPick: (value: string) => boolean;
};

function ContentControlDropdownItem({ item, MenuItem, onPick }: ContentControlDropdownItemProps) {
  const handleClick = useCallback(() => onPick(item.value), [item.value, onPick]);

  return <MenuItem onClick={handleClick}>{item.displayText}</MenuItem>;
}
