// packages/vue/src/components/FormattingBar.vue
<!--
  Vue port of packages/react/src/components/FormattingBar.tsx —
  a clean, minimal, controlled formatting bar for legal document editing.

  Controls (left to right):
  Undo Redo | Style ▾ | B I U | A▾ | ≡ 1. ◁ ▷

  Standalone + controlled, mirroring React: it owns no editor view. The host
  passes the selection's current formatting via `currentFormatting` and wires
  the emitted `format` / `undo` / `redo` events back into the document (React
  threads the same intent through its `onFormat` / `onUndo` / `onRedo` props).
  Everything else (font, size, highlight, comments) is reachable via keyboard
  shortcuts or the host app's chrome, matching React's minimal subset.

  Composes the same Vue `ui/` pickers the full <Toolbar> uses (StylePicker,
  ColorPicker, AlignmentButtons, ListButtons) so the two rails stay visually
  and behaviourally aligned.
-->
<template>
  <div
    class="docx-formatting-bar"
    :class="className"
    role="toolbar"
    :aria-label="t('formattingToolbar')"
    data-folio-toolbar="true"
  >
    <!-- Undo / Redo -->
    <span class="docx-formatting-bar__group" role="group" :aria-label="t('historyGroup')">
      <button
        type="button"
        class="docx-formatting-bar__btn"
        :disabled="disabled || !canUndo"
        :title="t('undoShortcut')"
        :aria-label="t('undo')"
        @mousedown.prevent="emit('undo')"
      >
        <MaterialSymbol name="undo" :size="18" />
      </button>
      <button
        type="button"
        class="docx-formatting-bar__btn"
        :disabled="disabled || !canRedo"
        :title="t('redoShortcut')"
        :aria-label="t('redo')"
        @mousedown.prevent="emit('redo')"
      >
        <MaterialSymbol name="redo" :size="18" />
      </button>
    </span>

    <span class="docx-formatting-bar__divider" role="separator" />

    <!-- Paragraph style -->
    <template v-if="showStylePicker">
      <!-- `styles` is passed only when supplied so StylePicker keeps its own
           default-preset fallback (its prop is non-`undefined` under
           exactOptionalPropertyTypes). -->
      <StylePicker
        :value="currentFormatting.styleId ?? 'Normal'"
        v-bind="stylePickerStyles"
        :disabled="disabled"
        @change="(styleId: string) => emit('format', { type: 'applyStyle', value: styleId })"
      />
      <span class="docx-formatting-bar__divider" role="separator" />
    </template>

    <!-- Bold / Italic / Underline -->
    <span class="docx-formatting-bar__group" role="group" :aria-label="t('textFormattingGroup')">
      <button
        type="button"
        class="docx-formatting-bar__btn"
        :class="{ 'docx-formatting-bar__btn--active': currentFormatting.bold }"
        :disabled="disabled"
        :title="t('boldShortcut')"
        :aria-label="t('bold')"
        :aria-pressed="!!currentFormatting.bold"
        @mousedown.prevent="emit('format', 'bold')"
      >
        <MaterialSymbol name="format_bold" :size="18" />
      </button>
      <button
        type="button"
        class="docx-formatting-bar__btn"
        :class="{ 'docx-formatting-bar__btn--active': currentFormatting.italic }"
        :disabled="disabled"
        :title="t('italicShortcut')"
        :aria-label="t('italic')"
        :aria-pressed="!!currentFormatting.italic"
        @mousedown.prevent="emit('format', 'italic')"
      >
        <MaterialSymbol name="format_italic" :size="18" />
      </button>
      <button
        type="button"
        class="docx-formatting-bar__btn"
        :class="{ 'docx-formatting-bar__btn--active': currentFormatting.underline }"
        :disabled="disabled"
        :title="t('underlineShortcut')"
        :aria-label="t('underline')"
        :aria-pressed="!!currentFormatting.underline"
        @mousedown.prevent="emit('format', 'underline')"
      >
        <MaterialSymbol name="format_underlined" :size="18" />
      </button>
    </span>

    <!-- Text color -->
    <template v-if="showTextColorPicker">
      <span class="docx-formatting-bar__divider" role="separator" />
      <ColorPicker
        mode="text"
        :value="textColorHex"
        :theme="theme ?? null"
        :disabled="disabled"
        @change="onTextColor"
      />
    </template>

    <span class="docx-formatting-bar__divider" role="separator" />

    <!-- Alignment -->
    <AlignmentButtons
      v-if="showAlignmentButtons"
      :value="currentFormatting.alignment ?? 'left'"
      :disabled="disabled"
      @change="
        (alignment: ParagraphAlignment) => emit('format', { type: 'alignment', value: alignment })
      "
    />

    <!-- Lists + indent -->
    <ListButtons
      v-if="showListButtons"
      :list-state="listState"
      :disabled="disabled"
      :can-outdent="canOutdent"
      @bullet-list="emit('format', 'bulletList')"
      @numbered-list="emit('format', 'numberedList')"
      @indent="emit('format', 'indent')"
      @outdent="emit('format', 'outdent')"
    />
  </div>
</template>

<script setup lang="ts">
import { computed } from "vue";
import MaterialSymbol from "./ui/MaterialSymbol.vue";
import StylePicker from "./ui/StylePicker.vue";
import AlignmentButtons from "./ui/AlignmentButtons.vue";
import ListButtons from "./ui/ListButtons.vue";
import { createDefaultListState } from "../utils/listState";
import { useTranslation } from "../i18n";
import { useFolioUI } from "../ui/folio-ui";

// Resolve ColorPicker from the FolioUI injection provider so a host
// `components.ColorPicker` override renders here; falls back to the package
// default (ui/ColorPicker.vue) when rendered outside a provider.
const { ColorPicker } = useFolioUI();
import type { ColorValue } from "@stll/folio-core/types/document";
import type { ListState } from "../utils/listState";
import type { ParagraphAlignment } from "./ui/AlignmentButtons.types";
import type { StyleOption } from "./ui/StylePicker.types";
import type {
  FormattingAction,
  FormattingBarProps,
  SelectionFormatting,
} from "./FormattingBar.types";

const props = withDefaults(defineProps<FormattingBarProps>(), {
  disabled: false,
  canUndo: false,
  canRedo: false,
  showStylePicker: true,
  showTextColorPicker: true,
  showAlignmentButtons: true,
  showListButtons: true,
});

const emit = defineEmits<{
  (e: "format", action: FormattingAction): void;
  (e: "undo"): void;
  (e: "redo"): void;
}>();

const { t } = useTranslation();

const currentFormatting = computed<SelectionFormatting>(() => props.currentFormatting ?? {});

// Omit `styles` entirely when the host passes none, so StylePicker falls back
// to its built-in presets instead of receiving `undefined`.
const stylePickerStyles = computed<{ styles: StyleOption[] } | Record<string, never>>(() =>
  props.documentStyles ? { styles: props.documentStyles } : {},
);

// ListButtons requires a concrete ListState (its prop is non-`undefined` under
// exactOptionalPropertyTypes); fall back to the empty default like React does.
const listState = computed<ListState>(
  () => currentFormatting.value.listState ?? createDefaultListState(),
);

// Hex (no `#`, uppercase) of the applied text color, matching the active
// swatch in the picker — mirrors Toolbar.vue's `currentTextColorHex`.
const textColorHex = computed<string | undefined>(() => {
  const color = currentFormatting.value.color;
  return color ? color.replace(/^#/, "").toUpperCase() : undefined;
});

// Outdent is only meaningful in a nested list level or when the paragraph
// already carries a left indent — mirrors Toolbar.vue's `canOutdent`.
const canOutdent = computed(() => {
  const current = listState.value;
  const inNestedList = current.isInList && current.level > 0;
  return inNestedList || (currentFormatting.value.indentLeft ?? 0) > 0;
});

function onTextColor(color: ColorValue | string) {
  emit("format", { type: "textColor", value: color });
}
</script>

<style scoped>
.docx-formatting-bar {
  display: flex;
  align-items: center;
  gap: 1px;
  width: 100%;
  height: 48px;
  padding: 0 16px;
  overflow-x: auto;
  border-bottom: 1px solid var(--doc-border);
  background: var(--doc-page);
  scrollbar-width: none;
}
.docx-formatting-bar::-webkit-scrollbar {
  display: none;
}
.docx-formatting-bar__group {
  display: inline-flex;
  align-items: center;
  gap: 2px;
}
.docx-formatting-bar__btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  min-width: 32px;
  height: 32px;
  border: none;
  border-radius: 6px;
  background: transparent;
  color: var(--doc-text-muted);
  cursor: pointer;
  flex-shrink: 0;
  transition:
    background-color 0.1s ease,
    color 0.1s ease;
}
.docx-formatting-bar__btn:focus-visible {
  outline: 2px solid var(--doc-primary);
  outline-offset: 2px;
}
.docx-formatting-bar__btn:hover:not(:disabled) {
  background: var(--doc-primary-light);
  color: var(--doc-text);
}
.docx-formatting-bar__btn--active,
.docx-formatting-bar__btn--active:hover {
  background: var(--doc-primary-light);
  color: var(--doc-text);
}
.docx-formatting-bar__btn:disabled {
  cursor: not-allowed;
  opacity: 0.35;
}
.docx-formatting-bar__divider {
  width: 1px;
  height: 24px;
  margin: 0 8px;
  background: var(--doc-border);
  flex-shrink: 0;
}
</style>

// packages/react/src/components/FormattingBar.tsx
/**
 * FormattingBar — clean, minimal toolbar for legal document editing.
 *
 * Controls (left to right):
 * Undo Redo | Style ▾ | B I U | A▾ | ≡▾ 1. • ◁ ▷
 *
 * Everything else (font, size, strikethrough, highlight, comments,
 * editing mode) is accessible via keyboard shortcuts or host app chrome.
 */

import React, { useCallback, useEffect, useRef, useState } from "react";
import type { CSSProperties, ReactNode } from "react";

import {
  BaselineIcon,
  BoldIcon,
  ChevronDownIcon,
  ImageIcon,
  ItalicIcon,
  MoreHorizontalIcon,
  PilcrowIcon,
  Redo2Icon,
  SeparatorHorizontalIcon,
  TableIcon,
  TableOfContentsIcon,
  UnderlineIcon,
  Undo2Icon,
} from "lucide-react";
import { useTranslations } from "use-intl";

import type { ParagraphAlignment } from "@stll/folio-core/types/document";
import { cn } from "../lib/utils";
import { useFolioUI } from "../ui/folio-ui";
import type { ColorPreset } from "../ui/folio-ui";
import { containedHandler } from "../utils/contained-handler";
import { ToolbarButton, ToolbarGroup, ToolbarSeparator } from "./toolbarPrimitives";
import type { ToolbarProps, FormattingAction } from "./toolbarPrimitives";
import { AlignmentButtons } from "./ui/AlignmentButtons";
import { FontPicker } from "./ui/FontPicker";
import { FontSizePicker } from "./ui/FontSizePicker";
import { ListButtons, createDefaultListState } from "./ui/ListButtons";
import { StylePicker } from "./ui/StylePicker";

const ICON_SIZE = 16;
const INLINE_SECONDARY_CONTROLS_MIN_WIDTH = 760;

/** Default grid the Insert Table button requests (the toolbar has no size picker). */
const DEFAULT_TABLE_ROWS = 2;
const DEFAULT_TABLE_COLUMNS = 2;

/** Document color presets — hex values for OOXML compatibility. */
const DOCUMENT_COLOR_PRESETS: ColorPreset[] = [
  { label: "Black", value: "000000" },
  { label: "White", value: "FFFFFF" },
  { label: "Dark Red", value: "C00000" },
  { label: "Red", value: "FF0000" },
  { label: "Orange", value: "FFC000" },
  { label: "Yellow", value: "FFFF00" },
  { label: "Light Green", value: "92D050" },
  { label: "Green", value: "00B050" },
  { label: "Teal", value: "008080" },
  { label: "Light Blue", value: "00B0F0" },
  { label: "Blue", value: "0070C0" },
  { label: "Dark Blue", value: "002060" },
  { label: "Purple", value: "7030A0" },
  { label: "Dark Gray", value: "404040" },
  { label: "Medium Gray", value: "808080" },
  { label: "Light Gray", value: "C0C0C0" },
];

export type FormattingBarProps = {
  children?: ReactNode;
  /** Host controls that should stay in the primary row before text formatting */
  priorityExtra?: ReactNode;
  /** Extra controls rendered inline in the center column (after formatting buttons) */
  inlineExtra?: ReactNode;
  /** Display label for the style picker when the backing document is hydrating. */
  stylePickerLabel?: string | undefined;
  /** Computed preview style for the hydrating style picker label. */
  stylePickerLabelStyle?: CSSProperties | undefined;
  inline?: boolean;
} & ToolbarProps;

export function FormattingBar(props: FormattingBarProps) {
  const {
    currentFormatting = {},
    onFormat,
    onUndo,
    onRedo,
    canUndo = false,
    canRedo = false,
    disabled = false,
    className,
    style,
    enableShortcuts = true,
    editorRef,
    children,
    showStylePicker = true,
    showFontPicker = true,
    showFontSizePicker = true,
    showTextColorPicker = true,
    showAlignmentButtons = true,
    showListButtons = true,
    documentStyles,
    theme,
    onRefocusEditor,
    onInsertImage,
    onInsertTable,
    showTableInsert = true,
    onInsertPageBreak,
    onInsertTOC,
    priorityExtra,
    inlineExtra,
    stylePickerLabel,
    stylePickerLabelStyle,
    inline = false,
  } = props;

  const folioUI = useFolioUI();
  const { Root: Menu, Trigger: MenuTrigger, Popup: MenuPopup } = folioUI.Menu;
  const ColorPicker = folioUI.ColorPicker;
  const t = useTranslations("folio");
  const barRef = useRef<HTMLDivElement>(null);
  const [showSecondaryInline, setShowSecondaryInline] = useState(false);

  const handleFormat = useCallback(
    (action: FormattingAction) => {
      if (!disabled && onFormat) {
        onFormat(action);
      }
    },
    [disabled, onFormat],
  );

  const handleUndo = useCallback(() => {
    if (!disabled && canUndo && onUndo) {
      onUndo();
    }
  }, [disabled, canUndo, onUndo]);

  const handleRedo = useCallback(() => {
    if (!disabled && canRedo && onRedo) {
      onRedo();
    }
  }, [disabled, canRedo, onRedo]);

  const handleFontFamilyChange = useCallback(
    (fontFamily: string) => {
      if (!disabled && onFormat) {
        onFormat({ type: "fontFamily", value: fontFamily });
        requestAnimationFrame(() => onRefocusEditor?.());
      }
    },
    [disabled, onFormat, onRefocusEditor],
  );

  const handleFontSizeChange = useCallback(
    (sizePt: number) => {
      if (!disabled && onFormat) {
        onFormat({ type: "fontSize", value: sizePt });
        requestAnimationFrame(() => onRefocusEditor?.());
      }
    },
    [disabled, onFormat, onRefocusEditor],
  );

  const handleTextColorSelect = useCallback(
    (hex: string) => {
      if (!disabled && onFormat) {
        onFormat({ type: "textColor", value: { rgb: hex } });
        requestAnimationFrame(() => onRefocusEditor?.());
      }
    },
    [disabled, onFormat, onRefocusEditor],
  );

  const handleTextColorClear = useCallback(() => {
    if (!disabled && onFormat) {
      onFormat({ type: "textColor", value: { auto: true } });
      requestAnimationFrame(() => onRefocusEditor?.());
    }
  }, [disabled, onFormat, onRefocusEditor]);

  const handleAlignmentChange = useCallback(
    (alignment: ParagraphAlignment) => {
      if (!disabled && onFormat) {
        onFormat({ type: "alignment", value: alignment });
      }
    },
    [disabled, onFormat],
  );

  const handleToggleDirection = useCallback(() => {
    if (!disabled && onFormat) {
      onFormat({ type: "toggleDirection" });
    }
  }, [disabled, onFormat]);

  const handleBulletList = useCallback(() => {
    if (!disabled && onFormat) {
      onFormat("bulletList");
    }
  }, [disabled, onFormat]);

  const handleNumberedList = useCallback(() => {
    if (!disabled && onFormat) {
      onFormat("numberedList");
    }
  }, [disabled, onFormat]);

  const handleIndent = useCallback(() => {
    if (!disabled && onFormat) {
      onFormat("indent");
    }
  }, [disabled, onFormat]);

  const handleOutdent = useCallback(() => {
    if (!disabled && onFormat) {
      onFormat("outdent");
    }
  }, [disabled, onFormat]);

  const handleStyleChange = useCallback(
    (styleId: string) => {
      if (!disabled && onFormat) {
        onFormat({ type: "applyStyle", value: styleId });
        requestAnimationFrame(() => onRefocusEditor?.());
      }
    },
    [disabled, onFormat, onRefocusEditor],
  );

  // After an insert, return focus to the editor so the caret lands in the new
  // content. Mouse clicks refocus via the bar's mouse-up handler, but keyboard
  // activation (Tab + Enter/Space) does not, so each insert refocuses itself.
  const handleInsertImage = useCallback(() => {
    if (!disabled && onInsertImage) {
      onInsertImage();
      requestAnimationFrame(() => onRefocusEditor?.());
    }
  }, [disabled, onInsertImage, onRefocusEditor]);

  const handleInsertTable = useCallback(() => {
    if (!disabled && onInsertTable) {
      onInsertTable(DEFAULT_TABLE_ROWS, DEFAULT_TABLE_COLUMNS);
      requestAnimationFrame(() => onRefocusEditor?.());
    }
  }, [disabled, onInsertTable, onRefocusEditor]);

  const handleInsertPageBreak = useCallback(() => {
    if (!disabled && onInsertPageBreak) {
      onInsertPageBreak();
      requestAnimationFrame(() => onRefocusEditor?.());
    }
  }, [disabled, onInsertPageBreak, onRefocusEditor]);

  const handleInsertTOC = useCallback(() => {
    if (!disabled && onInsertTOC) {
      onInsertTOC();
      requestAnimationFrame(() => onRefocusEditor?.());
    }
  }, [disabled, onInsertTOC, onRefocusEditor]);

  const showTableButton = showTableInsert && Boolean(onInsertTable);
  const hasInsertControls =
    Boolean(onInsertImage) || showTableButton || Boolean(onInsertPageBreak) || Boolean(onInsertTOC);

  // Keyboard shortcuts
  useEffect(() => {
    if (!enableShortcuts) {
      return;
    }

    const claimShortcut = (event: KeyboardEvent) => {
      event.preventDefault();
      event.stopPropagation();
      event.stopImmediatePropagation();
    };

    const handleKeyDown = (event: KeyboardEvent) => {
      if (!(event.target instanceof HTMLElement)) {
        return;
      }
      const target = event.target;
      const editorContainer = editorRef?.current;
      const barContainer = barRef.current;
      if (!editorContainer?.contains(target) && !barContainer?.contains(target)) {
        return;
      }

      const isCtrl = event.ctrlKey || event.metaKey;

      // Cmd+Enter — page break
      if (isCtrl && event.key === "Enter") {
        claimShortcut(event);
        handleFormat("insertPageBreak");
        return;
      }

      // Cmd+Shift shortcuts
      if (isCtrl && event.shiftKey) {
        switch (event.key) {
          case "=":
          case "+":
            claimShortcut(event);
            handleFormat("superscript");
            return;
          case "8":
            claimShortcut(event);
            handleBulletList();
            return;
          default:
            break;
        }
      }

      if (!isCtrl || event.altKey) {
        return;
      }

      switch (event.key.toLowerCase()) {
        case "b":
          claimShortcut(event);
          handleFormat("bold");
          break;
        case "i":
          claimShortcut(event);
          handleFormat("italic");
          break;
        case "u":
          claimShortcut(event);
          handleFormat("underline");
          break;
        case "d":
          claimShortcut(event);
          handleFormat("strikethrough");
          break;
        case "l":
          claimShortcut(event);
          handleAlignmentChange("left");
          break;
        case "e":
          claimShortcut(event);
          handleAlignmentChange("center");
          break;
        case "r":
          claimShortcut(event);
          handleAlignmentChange("right");
          break;
        case "j":
          claimShortcut(event);
          handleAlignmentChange("both");
          break;
        case "=":
          claimShortcut(event);
          handleFormat("subscript");
          break;
        case "]":
          claimShortcut(event);
          handleIndent();
          break;
        case "[":
          claimShortcut(event);
          handleOutdent();
          break;
        default:
          break;
      }
    };

    document.addEventListener("keydown", handleKeyDown, true);
    return () => document.removeEventListener("keydown", handleKeyDown, true);
  }, [
    enableShortcuts,
    handleFormat,
    handleAlignmentChange,
    handleBulletList,
    handleIndent,
    handleOutdent,
    editorRef,
  ]);

  useEffect(() => {
    const bar = barRef.current;
    if (!bar || inline) {
      setShowSecondaryInline(inline);
      return undefined;
    }

    const update = () => {
      const shouldShow = bar.getBoundingClientRect().width >= INLINE_SECONDARY_CONTROLS_MIN_WIDTH;
      setShowSecondaryInline((current) => (current === shouldShow ? current : shouldShow));
    };

    update();
    const observer = new ResizeObserver(update);
    observer.observe(bar);

    return () => {
      observer.disconnect();
    };
  }, [inline]);

  const handleBarMouseDown = useCallback((e: React.MouseEvent) => {
    if (!(e.target instanceof HTMLElement)) {
      e.preventDefault();
      return;
    }
    const target = e.target;
    if (target.tagName !== "INPUT" && target.tagName !== "SELECT") {
      e.preventDefault();
    }
  }, []);

  const handleBarMouseUp = useCallback(() => {
    requestAnimationFrame(() => onRefocusEditor?.());
  }, [onRefocusEditor]);

  const secondaryControls = (
    <>
      <ToolbarGroup label={t("fontGroup")}>
        {showFontPicker && (
          <FontPicker
            value={currentFormatting.fontFamily || "Arial"}
            onChange={handleFontFamilyChange}
            disabled={disabled}
            width={108}
            placeholder="Arial"
          />
        )}
        {showFontSizePicker && (
          <FontSizePicker
            value={
              currentFormatting.fontSize !== undefined ? currentFormatting.fontSize / 2 : undefined
            }
            onChange={handleFontSizeChange}
            disabled={disabled}
            placeholder={t("fontSize")}
          />
        )}
        {showTextColorPicker && (
          <ColorPicker
            presets={DOCUMENT_COLOR_PRESETS}
            columns={8}
            value={currentFormatting.color?.replace(/^#/u, "").toUpperCase()}
            onSelect={handleTextColorSelect}
            onClear={handleTextColorClear}
          >
            <ToolbarButton disabled={disabled} title={t("fontColor")} ariaLabel={t("fontColor")}>
              <div className="flex flex-col items-center gap-0">
                <BaselineIcon size={ICON_SIZE} />
                <span
                  className="mt-[-2px] h-1 w-4 rounded-sm"
                  style={{
                    backgroundColor: (() => {
                      if (currentFormatting.color) {
                        return (() => {
                          if (currentFormatting.color.startsWith("#")) {
                            return currentFormatting.color;
                          }
                          return `#${currentFormatting.color}`;
                        })();
                      }
                      return "#000000";
                    })(),
                  }}
                />
              </div>
              <ChevronDownIcon size={10} />
            </ToolbarButton>
          </ColorPicker>
        )}
      </ToolbarGroup>

      {showAlignmentButtons && (
        <ToolbarGroup label={t("alignmentGroup")}>
          <AlignmentButtons
            value={currentFormatting.alignment || "left"}
            onChange={handleAlignmentChange}
            disabled={disabled}
          />
          <ToolbarButton
            onClick={handleToggleDirection}
            active={currentFormatting.bidi}
            disabled={disabled}
            title={t("textDirection")}
            ariaLabel={t("textDirection")}
          >
            <PilcrowIcon size={ICON_SIZE} />
          </ToolbarButton>
        </ToolbarGroup>
      )}

      {showListButtons && (
        <ToolbarGroup label={t("listsGroup")}>
          <ListButtons
            listState={currentFormatting.listState || createDefaultListState()}
            onBulletList={handleBulletList}
            onNumberedList={handleNumberedList}
            onIndent={handleIndent}
            onOutdent={handleOutdent}
            disabled={disabled}
            showIndentButtons={true}
            compact
            hasIndent={(currentFormatting.indentLeft ?? 0) > 0}
          />
        </ToolbarGroup>
      )}

      {inlineExtra}
    </>
  );

  return (
    <div
      ref={barRef}
      className={cn(
        !inline &&
          "flex h-12 w-full items-center gap-0.5 overflow-hidden border-b border-[var(--doc-border)] bg-[var(--doc-page)] px-2 sm:px-4",
        className,
      )}
      style={inline ? { display: "contents", ...style } : style}
      role="toolbar"
      aria-label={t("formattingToolbar")}
      tabIndex={-1}
      data-folio-toolbar="true"
      onMouseDown={inline ? undefined : containedHandler(barRef, handleBarMouseDown)}
      onMouseUp={inline ? undefined : containedHandler(barRef, handleBarMouseUp)}
    >
      {/* Formatting controls */}
      <div className="flex min-w-0 flex-1 [scrollbar-width:none] items-center gap-0.5 overflow-x-auto overflow-y-hidden overscroll-x-contain [&::-webkit-scrollbar]:hidden">
        {/* Undo / Redo */}
        <ToolbarGroup className="gap-0" label={t("historyGroup")}>
          <ToolbarButton
            className="h-8 w-7 rounded-e-none disabled:opacity-[0.35]"
            onClick={handleUndo}
            disabled={disabled || !canUndo}
            title={t("undoShortcut")}
            ariaLabel={t("undo")}
          >
            <Undo2Icon size={ICON_SIZE} />
          </ToolbarButton>
          <ToolbarButton
            className="h-8 w-7 rounded-s-none disabled:opacity-[0.35]"
            onClick={handleRedo}
            disabled={disabled || !canRedo}
            title={t("redoShortcut")}
            ariaLabel={t("redo")}
          >
            <Redo2Icon size={ICON_SIZE} />
          </ToolbarButton>
        </ToolbarGroup>

        <ToolbarSeparator />

        {/* Paragraph style gallery */}
        {showStylePicker && (
          <>
            <StylePicker
              value={currentFormatting.styleId || "Normal"}
              onChange={handleStyleChange}
              styles={documentStyles}
              theme={theme}
              disabled={disabled}
              displayLabel={stylePickerLabel}
              displayLabelStyle={stylePickerLabelStyle}
              className="shrink-0"
              width="clamp(112px, 15vw, 140px)"
            />
            <ToolbarSeparator />
          </>
        )}

        {priorityExtra && (
          <>
            {priorityExtra}
            <ToolbarSeparator />
          </>
        )}

        {/* Bold, Italic, Underline */}
        <ToolbarGroup label={t("textFormattingGroup")}>
          <ToolbarButton
            onClick={() => handleFormat("bold")}
            active={currentFormatting.bold}
            disabled={disabled}
            title={t("boldShortcut")}
            ariaLabel={t("bold")}
          >
            <BoldIcon size={ICON_SIZE} />
          </ToolbarButton>
          <ToolbarButton
            onClick={() => handleFormat("italic")}
            active={currentFormatting.italic}
            disabled={disabled}
            title={t("italicShortcut")}
            ariaLabel={t("italic")}
          >
            <ItalicIcon size={ICON_SIZE} />
          </ToolbarButton>
          <ToolbarButton
            onClick={() => handleFormat("underline")}
            active={currentFormatting.underline}
            disabled={disabled}
            title={t("underlineShortcut")}
            ariaLabel={t("underline")}
          >
            <UnderlineIcon size={ICON_SIZE} />
          </ToolbarButton>
        </ToolbarGroup>

        {/* Insert group — each control is opt-in: it renders only when its
            handler (and flag, for tables) is provided by the consumer. */}
        {hasInsertControls && (
          <>
            <ToolbarSeparator />
            <ToolbarGroup label={t("insertGroup")}>
              {onInsertImage && (
                <ToolbarButton
                  onClick={handleInsertImage}
                  disabled={disabled}
                  title={t("insertImage")}
                  ariaLabel={t("insertImage")}
                >
                  <ImageIcon size={ICON_SIZE} />
                </ToolbarButton>
              )}
              {showTableButton && (
                <ToolbarButton
                  onClick={handleInsertTable}
                  disabled={disabled}
                  title={t("insertTable")}
                  ariaLabel={t("insertTable")}
                  testId="toolbar-insert-table"
                >
                  <TableIcon size={ICON_SIZE} />
                </ToolbarButton>
              )}
              {onInsertPageBreak && (
                <ToolbarButton
                  onClick={handleInsertPageBreak}
                  disabled={disabled}
                  title={t("insertPageBreak")}
                  ariaLabel={t("insertPageBreak")}
                >
                  <SeparatorHorizontalIcon size={ICON_SIZE} />
                </ToolbarButton>
              )}
              {onInsertTOC && (
                <ToolbarButton
                  onClick={handleInsertTOC}
                  disabled={disabled}
                  title={t("insertTableOfContents")}
                  ariaLabel={t("insertTableOfContents")}
                >
                  <TableOfContentsIcon size={ICON_SIZE} />
                </ToolbarButton>
              )}
            </ToolbarGroup>
          </>
        )}

        {showSecondaryInline ? (
          <>
            <ToolbarSeparator />
            {secondaryControls}
          </>
        ) : (
          <>
            <ToolbarSeparator />
            <Menu>
              <MenuTrigger
                render={
                  <button
                    type="button"
                    className="flex h-8 w-8 shrink-0 items-center justify-center rounded-md text-[var(--doc-text-muted)] transition-colors duration-100 hover:bg-[var(--doc-primary-light)] hover:text-[var(--doc-text)]"
                    aria-label={t("moreFormatting")}
                    title={t("moreFormatting")}
                  />
                }
              >
                <MoreHorizontalIcon size={ICON_SIZE} />
              </MenuTrigger>
              <MenuPopup align="end" className="max-w-[min(520px,calc(100vw-24px))]">
                <div className="flex w-[min(480px,calc(100vw-48px))] flex-wrap items-center gap-1 p-1">
                  {secondaryControls}
                </div>
              </MenuPopup>
            </Menu>
          </>
        )}
      </div>

      {/* Host extras (track changes, etc.) */}
      <div className="ms-auto flex shrink-0 items-center gap-1">{children}</div>
    </div>
  );
}
