// packages/vue/src/components/ui/ListButtons.vue
<!--
  Vue port of packages/react/src/components/ui/ListButtons.tsx.
  Bullet / numbered toggles + indent / outdent buttons. Same emit
  contract; the caller dispatches the actual prosemirror commands.
-->
<template>
  <span class="docx-list-btns">
    <button
      type="button"
      class="docx-list-btns__btn"
      :class="{ 'docx-list-btns__btn--active': listState?.isInList && listState?.type === 'bullet' }"
      :disabled="disabled"
      title="Bullet list"
      @click.prevent="$emit('bullet-list')"
    >
      <MaterialSymbol name="format_list_bulleted" :size="20" />
    </button>
    <button
      type="button"
      class="docx-list-btns__btn"
      :class="{ 'docx-list-btns__btn--active': listState?.isInList && listState?.type === 'numbered' }"
      :disabled="disabled"
      title="Numbered list"
      @click.prevent="$emit('numbered-list')"
    >
      <MaterialSymbol name="format_list_numbered" :size="20" />
    </button>
    <template v-if="showIndentButtons">
      <button
        type="button"
        class="docx-list-btns__btn"
        :disabled="disabled || !canOutdent"
        title="Decrease indent"
        @click.prevent="$emit('outdent')"
      >
        <MaterialSymbol name="format_indent_decrease" :size="20" />
      </button>
      <button
        type="button"
        class="docx-list-btns__btn"
        :disabled="disabled"
        title="Increase indent"
        @click.prevent="$emit('indent')"
      >
        <MaterialSymbol name="format_indent_increase" :size="20" />
      </button>
    </template>
  </span>
</template>

<script lang="ts">
// Re-exported for parity with React's ListButtons — consumers wiring list
// state pull these from the same module as the component. `<script setup>`
// can't carry re-exports, so they live in a plain block.
export type { ListState } from '../../utils/listState';
export { createDefaultListState } from '../../utils/listState';
</script>

<script setup lang="ts">
import MaterialSymbol from './MaterialSymbol.vue';
import type { ListState } from '../../utils/listState';

withDefaults(
  defineProps<{
    listState?: ListState;
    disabled?: boolean;
    showIndentButtons?: boolean;
    canOutdent?: boolean;
  }>(),
  { disabled: false, showIndentButtons: true, canOutdent: true }
);

defineEmits<{
  (e: 'bullet-list'): void;
  (e: 'numbered-list'): void;
  (e: 'indent'): void;
  (e: 'outdent'): void;
}>();
</script>

<style scoped>
.docx-list-btns {
  display: inline-flex;
  gap: 1px;
}
.docx-list-btns__btn {
  width: 28px;
  height: 28px;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  border: none;
  border-radius: 6px;
  background: transparent;
  color: var(--doc-text-muted);
  cursor: pointer;
}
.docx-list-btns__btn:hover:not(:disabled) {
  background: var(--doc-bg-hover);
  color: var(--doc-text);
}
.docx-list-btns__btn--active {
  background: var(--doc-text);
  color: var(--doc-on-primary);
}
.docx-list-btns__btn--active:hover {
  background: var(--doc-text);
}
/* Dark mode: --doc-text flips light, so the active list button would be a
   near-white slab. Use Word's accent toggle, matching Toolbar/AlignmentButtons
   and the React ListButtons. */
.ep-root.dark .docx-list-btns__btn--active,
.ep-root.dark .docx-list-btns__btn--active:hover {
  background: var(--doc-primary-light);
  color: var(--doc-primary);
}
.docx-list-btns__btn:disabled {
  opacity: 0.3;
  cursor: not-allowed;
}
</style>

// packages/react/src/components/ui/ListButtons.tsx
/**
 * List formatting buttons: bullet, numbered, indent, outdent.
 */

import { IndentDecreaseIcon, IndentIncreaseIcon, ListIcon, ListOrderedIcon } from "lucide-react";
import { useTranslations } from "use-intl";

import { cn } from "../../lib/utils";

export type ListType = "bullet" | "numbered" | "none";

export type ListState = {
  type: ListType;
  level: number;
  isInList: boolean;
  numId?: number;
};

export type ListButtonsProps = {
  listState?: ListState;
  onBulletList?: () => void;
  onNumberedList?: () => void;
  onIndent?: () => void;
  onOutdent?: () => void;
  disabled?: boolean;
  showIndentButtons?: boolean;
  compact?: boolean;
  hasIndent?: boolean;
};

export const createDefaultListState = (): ListState => ({
  type: "none",
  level: 0,
  isInList: false,
});

const ICON_SIZE = 16;

const btnCls = (active: boolean, disabled: boolean, compact: boolean) =>
  cn(
    "flex items-center justify-center rounded transition-colors",
    compact ? "size-7" : "size-8",
    active
      ? "bg-[var(--doc-primary-light)] text-[var(--doc-text)]"
      : "text-[var(--doc-text-muted)] hover:bg-[var(--doc-primary-light)]",
    disabled &&
      "cursor-not-allowed text-[var(--doc-text-subtle)] opacity-[0.16] disabled:hover:bg-transparent disabled:hover:text-[var(--doc-text-subtle)]",
  );

export function ListButtons({
  listState,
  onBulletList,
  onNumberedList,
  onIndent,
  onOutdent,
  disabled = false,
  showIndentButtons = true,
  compact = false,
  hasIndent = false,
}: ListButtonsProps) {
  const t = useTranslations("folio");
  const isBullet = listState?.type === "bullet";
  const isNumbered = listState?.type === "numbered";
  const isInList = listState?.isInList || isBullet || isNumbered;
  const canOutdent = (isInList && listState.level > 0) || hasIndent;

  return (
    <div className="inline-flex items-center gap-1" role="group" aria-label={t("listFormatting")}>
      <button
        aria-label={t("bulletList")}
        aria-pressed={isBullet}
        className={btnCls(isBullet, disabled, compact)}
        disabled={disabled}
        onClick={onBulletList}
        onMouseDown={(e) => e.preventDefault()}
        title={t("bulletList")}
        type="button"
      >
        <ListIcon size={ICON_SIZE} />
      </button>
      <button
        aria-label={t("numberedList")}
        aria-pressed={isNumbered}
        className={btnCls(isNumbered, disabled, compact)}
        disabled={disabled}
        onClick={onNumberedList}
        onMouseDown={(e) => e.preventDefault()}
        title={t("numberedList")}
        type="button"
      >
        <ListOrderedIcon size={ICON_SIZE} />
      </button>
      {showIndentButtons && (
        <>
          <span className="mx-1.5 h-5 w-px bg-[var(--doc-border)]" role="separator" />
          <button
            aria-label={t("decreaseIndent")}
            className={btnCls(false, disabled || !canOutdent, compact)}
            disabled={disabled || !canOutdent}
            onClick={onOutdent}
            onMouseDown={(e) => e.preventDefault()}
            title={t("decreaseIndent")}
            type="button"
          >
            <IndentDecreaseIcon size={ICON_SIZE} />
          </button>
          <button
            aria-label={t("increaseIndent")}
            className={btnCls(false, disabled, compact)}
            disabled={disabled}
            onClick={onIndent}
            onMouseDown={(e) => e.preventDefault()}
            title={t("increaseIndent")}
            type="button"
          >
            <IndentIncreaseIcon size={ICON_SIZE} />
          </button>
        </>
      )}
    </div>
  );
}
