// packages/react/src/components/DocumentOutline.tsx
/**
 * Document outline for the docx editor.
 *
 * Owns the outline's chrome (the column, rail or opened track, its header and
 * toggles) and the editor-specific data: heading positions over the full
 * document size (the paged editor virtualises pages). The active heading is
 * tracked once by the editor (`useActiveHeading`) and passed in, so every
 * surface marks the same one. The list of headings itself comes from the
 * injected OutlineRail (the consumer's design system, or folio's minimal
 * default), told which presentation it fills.
 *
 * The editor decides the surface from the width it has (see
 * `@stll/folio-core/panel-layout`): a `column` beside the page, a `rail` of heading ticks,
 * or an explicitly opened, width-clamped track beside the document.
 */

import type React from "react";
import { type RefObject, useCallback, useMemo, useRef } from "react";

import { PanelLeftOpenIcon, XIcon } from "lucide-react";
import { useTranslations } from "use-intl";

import type { HeadingInfo } from "@stll/folio-core/utils/headingCollector";
import type { OutlineDepth } from "@stll/folio-core/utils/outlineDepth";
import { useFolioUI } from "../ui/folio-ui";
import type { OutlineItem } from "../ui/folio-ui";
import { headingId } from "./hooks/useActiveHeading";
import { useDrawerFocus } from "./panelDrawer";
import { PANEL_METRICS } from "@stll/folio-core/panel-layout";

/** Where the outline sits: a column, a tick rail, or an opened in-flow panel. */
export type DocumentOutlineSurface = "column" | "expanded" | "rail";

const SURFACE_WIDTH = {
  column: PANEL_METRICS.outlineColumnWidth,
  rail: PANEL_METRICS.outlineRailWidth,
  expanded: PANEL_METRICS.outlineColumnWidth,
} as const satisfies Record<DocumentOutlineSurface, number>;

export type DocumentOutlineProps = {
  headings: HeadingInfo[];
  available: boolean;
  outlineDepth: OutlineDepth;
  onOutlineDepthChange: (depth: OutlineDepth) => void;
  scrollContainerRef: RefObject<HTMLDivElement | null>;
  /** Total ProseMirror document content size — drives proportional tick
   *  placement when pages are virtualised. */
  docSize: number;
  /** The heading the reader is in (its item id). */
  activeId: string | null;
  /** Jump to the heading with item id `id`. */
  onJump: (id: string) => void;
  surface: DocumentOutlineSurface;
  /** Rail: whether the full outline is open. */
  expanded?: boolean;
  /** Rail: open the full outline. */
  onExpand?: () => void;
  /** Close the opened outline (after a jump, Escape, or the close button). */
  onClose?: () => void;
  width?: number;
};

export const DocumentOutline: React.FC<DocumentOutlineProps> = ({
  headings,
  available,
  outlineDepth,
  onOutlineDepthChange,
  scrollContainerRef,
  docSize,
  activeId,
  onJump,
  surface,
  expanded,
  onExpand,
  onClose,
  width: widthOverride,
}) => {
  const t = useTranslations("folio");
  const OutlineRail = useFolioUI().OutlineRail;
  const navRef = useRef<HTMLElement>(null);
  useDrawerFocus(navRef, surface === "expanded" && onClose ? onClose : null);
  const controlMinimumStyle = {
    minWidth: PANEL_METRICS.controlMinimumSize,
    minHeight: PANEL_METRICS.controlMinimumSize,
  };

  const items = useMemo<OutlineItem[]>(
    () =>
      headings.map((heading) => {
        const item: OutlineItem = {
          id: headingId(heading),
          label: heading.text,
          level: heading.level,
        };
        if (typeof heading.pageNumber === "number") {
          item.meta = String(heading.pageNumber);
        }
        return item;
      }),
    [headings],
  );

  const pctById = useMemo(() => {
    const map = new Map<string, number>();
    if (docSize > 0) {
      for (const heading of headings) {
        map.set(headingId(heading), Math.min(99, Math.max(1, (heading.pmPos / docSize) * 100)));
      }
    }
    return map;
  }, [headings, docSize]);

  const handleJump = useCallback(
    (id: string) => {
      onJump(id);
      if (surface === "expanded") {
        onClose?.();
      }
    },
    [onClose, onJump, surface],
  );

  const resolvePct = useCallback((id: string) => pctById.get(id) ?? null, [pctById]);

  if (!available) {
    return null;
  }

  const outlineLabel = t("editor.showDocumentOutline");
  const width = widthOverride ?? SURFACE_WIDTH[surface];
  const rail = (
    <OutlineRail
      activeId={activeId}
      ariaLabel={outlineLabel}
      items={items}
      onJump={handleJump}
      panelWidth={width}
      presentation={surface === "rail" ? "rail" : "panel"}
      resolvePct={resolvePct}
      scrollContainerRef={scrollContainerRef}
      topOffset={0}
    />
  );

  if (surface === "rail") {
    return (
      <nav
        aria-label={outlineLabel}
        className="folio-outline folio-outline--rail"
        data-testid="folio-outline"
        data-folio-outline-surface="rail"
        style={{ width }}
      >
        <button
          aria-expanded={expanded ?? false}
          aria-label={outlineLabel}
          className="folio-outline-icon-button"
          data-testid="folio-outline-expand"
          onClick={onExpand}
          style={controlMinimumStyle}
          title={outlineLabel}
          type="button"
        >
          <PanelLeftOpenIcon aria-hidden="true" size={16} />
        </button>
        {rail}
      </nav>
    );
  }

  return (
    <nav
      ref={navRef}
      aria-label={outlineLabel}
      className={`folio-outline folio-outline--${surface === "expanded" ? "column" : surface}`}
      data-testid="folio-outline"
      data-folio-outline-surface={surface}
      style={{ width }}
    >
      <div className="folio-outline-header">
        <div className="folio-outline-heading-row">
          <span className="folio-outline-title">{t("editor.outlineTitle")}</span>
          {surface === "expanded" && onClose && (
            <button
              aria-label={t("common.closeDialog")}
              className="folio-outline-icon-button"
              onClick={onClose}
              style={controlMinimumStyle}
              title={t("common.closeDialog")}
              type="button"
            >
              <XIcon aria-hidden="true" size={16} />
            </button>
          )}
        </div>
        <label className="folio-outline-depth-control">
          <span>{t("editor.outlineDepthLabel")}</span>
          <select
            aria-label={t("editor.outlineDepthLabel")}
            onChange={(event) => {
              const value = event.currentTarget.value;
              if (value === "all") {
                onOutlineDepthChange("all");
                return;
              }
              onOutlineDepthChange(value === "3" ? 3 : 2);
            }}
            value={outlineDepth}
          >
            <option value={2}>{t("editor.outlineDepthTwo")}</option>
            <option value={3}>{t("editor.outlineDepthThree")}</option>
            <option value="all">{t("editor.outlineDepthAll")}</option>
          </select>
        </label>
      </div>
      {rail}
    </nav>
  );
};

// packages/vue/src/components/DocumentOutline.vue
<template>
  <nav
    v-if="available"
    ref="navRef"
    :aria-label="outlineLabel"
    class="folio-outline"
    :class="'folio-outline--' + surface"
    :data-folio-outline-surface="surface"
    data-testid="folio-outline"
    :style="{ width: surfaceWidth + 'px' }"
    :tabindex="surface === 'drawer' ? -1 : undefined"
  >
    <button
      v-if="surface === 'rail'"
      type="button"
      class="folio-outline-icon-button"
      data-testid="folio-outline-expand"
      :aria-label="outlineLabel"
      :aria-expanded="expanded"
      :title="outlineLabel"
      @click="emit('expand')"
    >
      <MaterialSymbol name="view_column" :size="16" aria-hidden="true" />
    </button>
    <div v-else class="folio-outline-header">
      <div class="folio-outline-heading-row">
        <span class="folio-outline-title">{{ t("editor.outlineTitle") }}</span>
        <button
          v-if="surface === 'drawer'"
          type="button"
          class="folio-outline-icon-button"
          :aria-label="t('common.closeDialog')"
          :title="t('common.closeDialog')"
          @click="emit('close')"
        >
          <MaterialSymbol name="close" :size="16" aria-hidden="true" />
        </button>
      </div>
      <label class="folio-outline-depth-control">
        <span>{{ t("editor.outlineDepthLabel") }}</span>
        <select
          :aria-label="t('editor.outlineDepthLabel')"
          :value="outlineDepth"
          @change="onDepthChange"
        >
          <option :value="2">{{ t("editor.outlineDepthTwo") }}</option>
          <option :value="3">{{ t("editor.outlineDepthThree") }}</option>
          <option value="all">{{ t("editor.outlineDepthAll") }}</option>
        </select>
      </label>
    </div>
    <OutlineRail
      :items="items"
      :get-scroll-container="getScrollContainer"
      :resolve-pct="resolvePct"
      :on-jump="handleJump"
      :active-id="activeId"
      :presentation="surface === 'rail' ? 'rail' : 'panel'"
      :panel-width="surfaceWidth"
      :top-offset="0"
      :aria-label="outlineLabel"
    />
  </nav>
</template>

<script setup lang="ts">
import { computed, ref } from "vue";
import type { HeadingInfo } from "@stll/folio-core/utils/headingCollector";
import type { OutlineDepth } from "@stll/folio-core/utils/outlineDepth";
import { PANEL_METRICS } from "@stll/folio-core/panel-layout";
import { type OutlineSurface, useOutlineDrawerFocus } from "../composables/useOutlineDrawerFocus";
import { useTranslation } from "../i18n";
import type { OutlineItem } from "../ui/folio-ui";
import { useFolioUI } from "../ui/folio-ui";
import MaterialSymbol from "./ui/MaterialSymbol.vue";

const SURFACE_WIDTH = {
  column: PANEL_METRICS.outlineColumnWidth,
  rail: PANEL_METRICS.outlineRailWidth,
  drawer: PANEL_METRICS.drawerWidth,
} as const satisfies Record<OutlineSurface, number>;

const props = withDefaults(
  defineProps<{
    headings: HeadingInfo[];
    available: boolean;
    outlineDepth: OutlineDepth;
    getScrollContainer: () => HTMLElement | null;
    docSize: number;
    activeId: string | null;
    surface: OutlineSurface;
    expanded?: boolean;
  }>(),
  { expanded: false },
);

const emit = defineEmits<{
  navigate: [pmPos: number];
  expand: [];
  close: [];
  outlineDepthChange: [depth: OutlineDepth];
}>();

const { t } = useTranslation();
const { OutlineRail } = useFolioUI();
const navRef = ref<HTMLElement | null>(null);
const closeDrawer = () => emit("close");
useOutlineDrawerFocus({
  surface: () => props.surface,
  available: () => props.available,
  navRef,
  onClose: closeDrawer,
});
const outlineLabel = computed(() => t("editor.showDocumentOutline"));
const onDepthChange = (event: Event) => {
  if (!(event.currentTarget instanceof HTMLSelectElement)) return;
  const value = event.currentTarget.value;
  if (value === "all") {
    emit("outlineDepthChange", "all");
    return;
  }
  emit("outlineDepthChange", value === "3" ? 3 : 2);
};
const surfaceWidth = computed(() => SURFACE_WIDTH[props.surface]);
const items = computed<OutlineItem[]>(() =>
  props.headings.map((heading) => ({
    id: String(heading.pmPos),
    label: heading.text,
    level: heading.level,
    ...(typeof heading.pageNumber === "number" ? { meta: String(heading.pageNumber) } : {}),
  })),
);
const pctById = computed(() => {
  const positions = new Map<string, number>();
  if (props.docSize > 0) {
    for (const heading of props.headings) {
      positions.set(
        String(heading.pmPos),
        Math.min(99, Math.max(1, (heading.pmPos / props.docSize) * 100)),
      );
    }
  }
  return positions;
});

const resolvePct = (id: string) => pctById.value.get(id) ?? null;
const handleJump = (id: string) => {
  emit("navigate", Number(id));
  if (props.surface === "drawer") emit("close");
};
</script>

<style scoped>
.folio-outline {
  display: flex;
  flex-direction: column;
  box-sizing: border-box;
  min-height: 0;
  background: var(--doc-page, white);
  color: var(--doc-text);
  font-size: 0.8125rem;
}
.folio-outline--column {
  flex: none;
  border-inline-end: 1px solid var(--doc-border);
}
.folio-outline--rail {
  position: relative;
  z-index: 30;
  flex: none;
  align-items: center;
  padding-block: 4px 8px;
  border-inline-end: 1px solid var(--doc-border);
}
.folio-outline--drawer {
  position: absolute;
  inset-block: 0;
  inset-inline-start: 0;
  z-index: 46;
  max-width: calc(100% - 16px);
  border-inline-end: 1px solid var(--doc-border);
  box-shadow: 0 8px 28px var(--doc-shadow-md);
}
.folio-outline-header {
  display: flex;
  flex: none;
  flex-direction: column;
  border-bottom: 1px solid var(--doc-border);
}
.folio-outline-heading-row {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 0.25rem;
  min-height: 2.25rem;
  padding-block: 0.25rem;
  padding-inline: 0.75rem 0.375rem;
}
.folio-outline-depth-control {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 0.25rem;
  min-height: 2rem;
  padding-block: 0.125rem;
  padding-inline: 0.75rem 0.375rem;
  color: var(--doc-text-muted);
  font-size: 0.6875rem;
}
.folio-outline-depth-control span {
  flex: 1 1 auto;
  min-width: 0;
  overflow-wrap: anywhere;
}
.folio-outline-depth-control select {
  flex: none;
  min-width: 32px;
  max-width: 60%;
  min-height: 2rem;
  padding-inline: 0.25rem;
  border: 1px solid var(--doc-border);
  border-radius: 0.25rem;
  background: var(--doc-page);
  color: var(--doc-text);
  font: inherit;
}
.folio-outline-title {
  font-size: 0.75rem;
  font-weight: 600;
  color: var(--doc-text-muted);
}
.folio-outline-icon-button {
  display: inline-flex;
  flex: none;
  align-items: center;
  justify-content: center;
  width: 1.5rem;
  height: 1.5rem;
  padding: 0;
  border: 0;
  border-radius: 0.25rem;
  background: transparent;
  color: var(--doc-text-muted);
  cursor: pointer;
}
.folio-outline-icon-button:hover,
.folio-outline-icon-button[aria-expanded="true"] {
  background: var(--doc-bg-hover);
  color: var(--doc-text);
}
.folio-outline-icon-button:focus-visible {
  outline: 2px solid var(--ring, var(--doc-primary));
  outline-offset: -2px;
}
@media (prefers-reduced-motion: no-preference) {
  .folio-outline--drawer {
    animation: folio-outline-fade-in 0.16s ease-out;
  }
}
@keyframes folio-outline-fade-in {
  from {
    opacity: 0;
  }
  to {
    opacity: 1;
  }
}
</style>
